#ifndef C23META_VECTOR_DROP_LAST
#define C23META_VECTOR_DROP_LAST

#define VECTOR32_DROP_LAST(X,N) _VECTOR32_DROP_LAST_C(X,N)
#define _VECTOR32_DROP_LAST_C(X,N) VECTOR32_TAKE(X,DEC5_SUB(VECTOR32_LENGTH(X),N))

#endif