#ifndef C23META_VECTOR32_FIND_INDEX
#define C23META_VECTOR32_FIND_INDEX

#define VECTOR32_FIND_INDEX(P,X) _VECTOR32_FIND_INDEX_C(P,VECTOR32_AS_TUPLE(X))
#define _VECTOR32_FIND_INDEX_C(P,X) _VECTOR32_FIND_INDEX_EVAL(_VECTOR32_FIND_INDEX(P,0,TUPLE_IS_EMPTY(X),X))
#define _VECTOR32_FIND_INDEX_EVAL(X)  _VECTOR32_FIND_INDEX_EVAL1(_VECTOR32_FIND_INDEX_EVAL1(_VECTOR32_FIND_INDEX_EVAL1(_VECTOR32_FIND_INDEX_EVAL1(X))))
#define _VECTOR32_FIND_INDEX_EVAL1(X) _VECTOR32_FIND_INDEX_EVAL2(_VECTOR32_FIND_INDEX_EVAL2(_VECTOR32_FIND_INDEX_EVAL2(_VECTOR32_FIND_INDEX_EVAL2(X))))
#define _VECTOR32_FIND_INDEX_EVAL2(X) _VECTOR32_FIND_INDEX_EVAL3(_VECTOR32_FIND_INDEX_EVAL3(_VECTOR32_FIND_INDEX_EVAL3(_VECTOR32_FIND_INDEX_EVAL3(X))))
#define _VECTOR32_FIND_INDEX_EVAL3(X) X

#define _VECTOR32_FIND_INDEX(P,R,N,X) CAT(_VECTOR32_FIND_INDEX_X, N)(P,R,X)
#define _VECTOR32_FIND_INDEX_X1(P,R,X) NOT_FOUND
#define _VECTOR32_FIND_INDEX_X0(P,R,X) CAT(_VECTOR32_FIND_INDEX_Y,P(TUPLE_FIRST(X)))(P,R,X)
#define _VECTOR32_FIND_INDEX_Y1(P,R,X) R
#define _VECTOR32_FIND_INDEX_Y0(P,R,X) _VECTOR32_FIND_INDEX_Z(P,DEC5_ADD(R,1),TUPLE_REST(X))
#define _VECTOR32_FIND_INDEX_Z(P,R,X) DEFER(_VECTOR32_FIND_INDEX_I)()(P,R,TUPLE_IS_EMPTY(X),X)
#define _VECTOR32_FIND_INDEX_I() _VECTOR32_FIND_INDEX

#endif