#ifndef C23META_VECTOR_IS_VECTOR
#define C23META_VECTOR_IS_VECTOR

#define IS_VECTOR32(X) _VECTOR32_IS_VECTOR32_C(X)
#define _VECTOR32_IS_VECTOR32_C(X) CAT(_VECTOR32_IS_VECTOR32_, IS_PAIR(X))(X)
#define _VECTOR32_IS_VECTOR32_0(X) 0
#define _VECTOR32_IS_VECTOR32_1(X) BOOL_AND(IS_DEC5(VECTOR32_LENGTH(X)), IS_TUPLE(VECTOR32_VALUES(X)))

#endif