#ifndef C23META_VECTOR_LENGTH
#define C23META_VECTOR_LENGTH

#define VECTOR32_LENGTH(X) _VECTOR32_LENGTH_EVAL(_VECTOR32_LENGTH X)
#define _VECTOR32_LENGTH_EVAL(X) X
#define _VECTOR32_LENGTH(L,V) L

#define VECTOR32_LENGTH_U32H(X) CAT(U32H_, VECTOR32_LENGTH(X))

#endif