#ifndef C23META_VECTOR_REST
#define C23META_VECTOR_REST

#define VECTOR32_REST(X) _VECTOR32_REST_C(X)
#define _VECTOR32_REST_C(X) (DEC5_SUB(VECTOR32_LENGTH(X),1),TUPLE_REST(VECTOR32_AS_TUPLE(X)))

#endif