#ifndef C23META_VECTOR_TAKE_LAST
#define C23META_VECTOR_TAKE_LAST

#define VECTOR32_TAKE_LAST(X,N) _VECTOR32_TAKE_LAST_C(X,N)
#define _VECTOR32_TAKE_LAST_C(X,N) VECTOR32_DROP(X,DEC5_SUB(VECTOR32_LENGTH(X),N))

#endif