#ifndef C23META_DEC5_DEC5
#define C23META_DEC5_DEC5

#include "cmp/cmp.h"
#include "math/math.h"

#define IS_DEC5(X) CAT(_IS_DEC5_,IS_ATOM(X))(X)
#define _IS_DEC5_0(X) 0
#define _IS_DEC5_1(X) ATOM_EQ(_IS_DEC5_CHECK,X)
#define _IS_DEC5_CHECK0 ATOM_CHECK
#define _IS_DEC5_CHECK1 ATOM_CHECK
#define _IS_DEC5_CHECK2 ATOM_CHECK
#define _IS_DEC5_CHECK3 ATOM_CHECK
#define _IS_DEC5_CHECK4 ATOM_CHECK
#define _IS_DEC5_CHECK5 ATOM_CHECK
#define _IS_DEC5_CHECK6 ATOM_CHECK
#define _IS_DEC5_CHECK7 ATOM_CHECK
#define _IS_DEC5_CHECK8 ATOM_CHECK
#define _IS_DEC5_CHECK9 ATOM_CHECK
#define _IS_DEC5_CHECK10 ATOM_CHECK
#define _IS_DEC5_CHECK11 ATOM_CHECK
#define _IS_DEC5_CHECK12 ATOM_CHECK
#define _IS_DEC5_CHECK13 ATOM_CHECK
#define _IS_DEC5_CHECK14 ATOM_CHECK
#define _IS_DEC5_CHECK15 ATOM_CHECK
#define _IS_DEC5_CHECK16 ATOM_CHECK
#define _IS_DEC5_CHECK17 ATOM_CHECK
#define _IS_DEC5_CHECK18 ATOM_CHECK
#define _IS_DEC5_CHECK19 ATOM_CHECK
#define _IS_DEC5_CHECK20 ATOM_CHECK
#define _IS_DEC5_CHECK21 ATOM_CHECK
#define _IS_DEC5_CHECK22 ATOM_CHECK
#define _IS_DEC5_CHECK23 ATOM_CHECK
#define _IS_DEC5_CHECK24 ATOM_CHECK
#define _IS_DEC5_CHECK25 ATOM_CHECK
#define _IS_DEC5_CHECK26 ATOM_CHECK
#define _IS_DEC5_CHECK27 ATOM_CHECK
#define _IS_DEC5_CHECK28 ATOM_CHECK
#define _IS_DEC5_CHECK29 ATOM_CHECK
#define _IS_DEC5_CHECK30 ATOM_CHECK
#define _IS_DEC5_CHECK31 ATOM_CHECK
#define _IS_DEC5_CHECK32 ATOM_CHECK

#endif