#ifndef C23META_LIST_APPLY
#define C23META_LIST_APPLY

#define LIST_APPLY(F,X) _LIST_APPLY_C(F,X)
#define _LIST_APPLY_C(F,X) _LIST_APPLY_EVAL(OBSTRUCT(_LIST_APPLY_CALL)(F _LIST_APPLY(LIST_IS_NIL(X),X)))
#define _LIST_APPLY_EVAL(...)  _LIST_APPLY_EVAL1(_LIST_APPLY_EVAL1(_LIST_APPLY_EVAL1(_LIST_APPLY_EVAL1( __VA_ARGS__))))
#define _LIST_APPLY_EVAL1(...) _LIST_APPLY_EVAL2(_LIST_APPLY_EVAL2(_LIST_APPLY_EVAL2(_LIST_APPLY_EVAL2( __VA_ARGS__))))
#define _LIST_APPLY_EVAL2(...) _LIST_APPLY_EVAL3(_LIST_APPLY_EVAL3(_LIST_APPLY_EVAL3(_LIST_APPLY_EVAL3( __VA_ARGS__))))
#define _LIST_APPLY_EVAL3(...) __VA_ARGS__

#define _LIST_APPLY(N,X) CAT(_LIST_APPLY_X, N)(X)
#define _LIST_APPLY_X1(X)
#define _LIST_APPLY_X0(X) ,LIST_FIRST(X)_LIST_APPLY_Y(LIST_REST(X))
#define _LIST_APPLY_Y(X) DEFER(_LIST_APPLY_I)()(LIST_IS_NIL(X),X)
#define _LIST_APPLY_I() _LIST_APPLY

#define _LIST_APPLY_CALL(F,...) F(__VA_ARGS__)

#endif