#ifndef C23META_LIST_AS_ARGS
#define C23META_LIST_AS_ARGS
#include <stdlib.h>


#define LIST_AS_ARGS(X) _LIST_AS_ARGS_C(X)
#define _LIST_AS_ARGS_C(X) _LIST_AS_ARGS_EVAL(DEFER(_LIST_AS_ARGS_REST)(_LIST_AS_ARGS(LIST_IS_NIL(X),X)))
#define _LIST_AS_ARGS_EVAL(X)  _LIST_AS_ARGS_EVAL1(_LIST_AS_ARGS_EVAL1(_LIST_AS_ARGS_EVAL1(_LIST_AS_ARGS_EVAL1(X))))
#define _LIST_AS_ARGS_EVAL1(X) _LIST_AS_ARGS_EVAL2(_LIST_AS_ARGS_EVAL2(_LIST_AS_ARGS_EVAL2(_LIST_AS_ARGS_EVAL2(X))))
#define _LIST_AS_ARGS_EVAL2(X) _LIST_AS_ARGS_EVAL3(_LIST_AS_ARGS_EVAL3(_LIST_AS_ARGS_EVAL3(_LIST_AS_ARGS_EVAL3(X))))
#define _LIST_AS_ARGS_EVAL3(X) X

#define _LIST_AS_ARGS(N,X) CAT(_LIST_AS_ARGS_X, N)(X)
#define _LIST_AS_ARGS_X1(X)
#define _LIST_AS_ARGS_X0(X) ,LIST_FIRST(X)_LIST_AS_ARGS_Y(LIST_REST(X))
#define _LIST_AS_ARGS_Y(X) DEFER(_LIST_AS_ARGS_I)()(LIST_IS_NIL(X),X)
#define _LIST_AS_ARGS_I() _LIST_AS_ARGS

#define _LIST_AS_ARGS_REST(X,...) (__VA_ARGS__)

#endif