#ifndef C23META_LIST_AS_ARRAY
#define C23META_LIST_AS_ARRAY

#define LIST_AS_ARRAY(X,...) _LIST_AS_ARRAY_C(X __VA_OPT__(,) __VA_ARGS__)
#define _LIST_AS_ARRAY_C(X,...) _LIST_AS_ARRAY(LIST_LENGTH(X), _LIST_AS_ARRAY_TYPE ## __VA_OPT__(1(__VA_ARGS__) IGNORE)(X), LIST_AS_ARGS(X))
#define _LIST_AS_ARRAY_EVAL(X) LIST_APPLY(_LIST_AS_ARRAY, X)
#define _LIST_AS_ARRAY(LEN,TYPE,ARGS) (TYPE[U32H_CONVERT(LEN)]){UNWRAP ARGS}

#define _LIST_AS_ARRAY_TYPE(X) typeof(LIST_FIRST(X))
#define _LIST_AS_ARRAY_TYPE1(T) T
#endif