#ifndef C23META_LIST_AS_TUPLE
#define C23META_LIST_AS_TUPLE

#define LIST_AS_TUPLE_VALUE(X) _LIST_AS_TUPLE_VALUE(CAT(_LISTVARNAME, __COUNTER__),X)
#define _LIST_AS_TUPLE_VALUE(VARNAME,X) ({LIST_AS_TUPLE(VARNAME,X); VARNAME;})

#define LIST_AS_TUPLE_DATA(VARNAME,X) TUPLE_AS_DATA(VARNAME,LIST_AS_TUPLE(X))

#define LIST_AS_TUPLE(X) LIST_AS_ARGS(X)

#endif