#ifndef C23META_LIST_FILTER
#define C23META_LIST_FILTER

#define LIST_FILTER(P,X) _LIST_FILTER_C(P,X)
#define _LIST_FILTER_C(P,X) _LIST_FILTER_EVAL(_LIST_FILTER(P,LIST_IS_NIL(X),X))
#define _LIST_FILTER_EVAL(X)  _LIST_FILTER_EVAL1(_LIST_FILTER_EVAL1(_LIST_FILTER_EVAL1(_LIST_FILTER_EVAL1(X))))
#define _LIST_FILTER_EVAL1(X) _LIST_FILTER_EVAL2(_LIST_FILTER_EVAL2(_LIST_FILTER_EVAL2(_LIST_FILTER_EVAL2(X))))
#define _LIST_FILTER_EVAL2(X) _LIST_FILTER_EVAL3(_LIST_FILTER_EVAL3(_LIST_FILTER_EVAL3(_LIST_FILTER_EVAL3(X))))
#define _LIST_FILTER_EVAL3(X) X

#define _LIST_FILTER(P,N,X) CAT(_LIST_FILTER_X, N)(P,X)
#define _LIST_FILTER_X1(P,X) LIST_NIL
#define _LIST_FILTER_X0(P,X) CAT(_LIST_FILTER_Y,P(LIST_FIRST(X)))(P,X)
#define _LIST_FILTER_Y1(P,X) (LIST_FIRST(X), _LIST_FILTER_Z(P,LIST_REST(X)))
#define _LIST_FILTER_Y0(P,X) _LIST_FILTER_Z(P,LIST_REST(X))
#define _LIST_FILTER_Z(P,X) DEFER(_LIST_FILTER_I)()(P,LIST_IS_NIL(X),X)
#define _LIST_FILTER_I() _LIST_FILTER

#endif