#ifndef C23META_LIST_FIND_INDEX
#define C23META_LIST_FIND_INDEX

#define LIST_FIND_INDEX(P,X) _LIST_FIND_INDEX_EVAL(_LIST_FIND_INDEX(P,U32_0,LIST_IS_NIL(X),X))
#define _LIST_FIND_INDEX_EVAL(X)  _LIST_FIND_INDEX_EVAL1(_LIST_FIND_INDEX_EVAL1(_LIST_FIND_INDEX_EVAL1(_LIST_FIND_INDEX_EVAL1(X))))
#define _LIST_FIND_INDEX_EVAL1(X) _LIST_FIND_INDEX_EVAL2(_LIST_FIND_INDEX_EVAL2(_LIST_FIND_INDEX_EVAL2(_LIST_FIND_INDEX_EVAL2(X))))
#define _LIST_FIND_INDEX_EVAL2(X) _LIST_FIND_INDEX_EVAL3(_LIST_FIND_INDEX_EVAL3(_LIST_FIND_INDEX_EVAL3(_LIST_FIND_INDEX_EVAL3(X))))
#define _LIST_FIND_INDEX_EVAL3(X) X

#define _LIST_FIND_INDEX(P,R,N,X) DEFER(CAT(_LIST_FIND_INDEX_X, N))(P,R,X)
#define _LIST_FIND_INDEX_X1(P,R,X) U32_MAX
#define _LIST_FIND_INDEX_X0(P,R,X) DEFER(CAT(_LIST_FIND_INDEX_Y,P(LIST_FIRST(X))))(P,R,X)
#define _LIST_FIND_INDEX_Y1(P,R,X) R
#define _LIST_FIND_INDEX_Y0(P,R,X) _LIST_FIND_INDEX_Z(P,U32_ADD(R,U32_1),LIST_REST(X))
#define _LIST_FIND_INDEX_Z(P,R,X) DEFER(_LIST_FIND_INDEX_I)()(P,R,LIST_IS_NIL(X),X)
#define _LIST_FIND_INDEX_I() _LIST_FIND_INDEX

#endif