#ifndef C23META_LIST_FOLDL
#define C23META_LIST_FOLDL

#define LIST_FOLDL(F,X,...) _LIST_FOLDL_C(F,X __VA_OPT__(,) __VA_ARGS__)
#define _LIST_FOLDL_C(F,X,...) _LIST_FOLDL_EVAL(_LIST_FOLDL(F,LIST_IS_NIL(X),_LIST_FOLDL_P ## __VA_OPT__(1)(X),_LIST_FOLDL_INIT ## __VA_OPT__(1(__VA_ARGS__) IGNORE) (X)))
#define _LIST_FOLDL_EVAL(X)  _LIST_FOLDL_EVAL1(_LIST_FOLDL_EVAL1(_LIST_FOLDL_EVAL1(_LIST_FOLDL_EVAL1(X))))
#define _LIST_FOLDL_EVAL1(X) _LIST_FOLDL_EVAL2(_LIST_FOLDL_EVAL2(_LIST_FOLDL_EVAL2(_LIST_FOLDL_EVAL2(X))))
#define _LIST_FOLDL_EVAL2(X) _LIST_FOLDL_EVAL3(_LIST_FOLDL_EVAL3(_LIST_FOLDL_EVAL3(_LIST_FOLDL_EVAL3(X))))
#define _LIST_FOLDL_EVAL3(X) X

#define _LIST_FOLDL_P(X) LIST_REST(X)
#define _LIST_FOLDL_P1(X) X

#define _LIST_FOLDL_INIT(X) LIST_FIRST(X)
#define _LIST_FOLDL_INIT1(I) I

#define _LIST_FOLDL(F,N,X,R) CAT(_LIST_FOLDL_X, N)(F,X,R)
#define _LIST_FOLDL_X1(F,X,R) R
#define _LIST_FOLDL_X0(F,X,R) _LIST_FOLDL_Y(F,LIST_REST(X),F(R,LIST_FIRST(X)))
#define _LIST_FOLDL_Y(F,X,R) DEFER(_LIST_FOLDL_I)()(F,LIST_IS_NIL(X),X,R)
#define _LIST_FOLDL_I() _LIST_FOLDL

#endif