#ifndef C23META_LIST_FOREACH
#define C23META_LIST_FOREACH

#define LIST_FOREACH(F,X) _LIST_FOREACH_C(F,X)
#define _LIST_FOREACH_C(F,X) _LIST_FOREACH_EVAL(_LIST_FOREACH(F,LIST_IS_NIL(X),X))
#define _LIST_FOREACH_EVAL(...)  _LIST_FOREACH_EVAL1(_LIST_FOREACH_EVAL1(_LIST_FOREACH_EVAL1(_LIST_FOREACH_EVAL1(__VA_ARGS__))))
#define _LIST_FOREACH_EVAL1(...) _LIST_FOREACH_EVAL2(_LIST_FOREACH_EVAL2(_LIST_FOREACH_EVAL2(_LIST_FOREACH_EVAL2(__VA_ARGS__))))
#define _LIST_FOREACH_EVAL2(...) _LIST_FOREACH_EVAL3(_LIST_FOREACH_EVAL3(_LIST_FOREACH_EVAL3(_LIST_FOREACH_EVAL3(__VA_ARGS__))))
#define _LIST_FOREACH_EVAL3(...) __VA_ARGS__
#define _LIST_FOREACH(F,N,X) CAT(_LIST_FOREACH_X, N)(F,X)
#define _LIST_FOREACH_X1(F,X)
#define _LIST_FOREACH_X0(F,X) F(LIST_FIRST(X))_LIST_FOREACH_Y(F,LIST_REST(X))
#define _LIST_FOREACH_Y(F,X) DEFER(_LIST_FOREACH_I)()(F,LIST_IS_NIL(X),X)
#define _LIST_FOREACH_I() _LIST_FOREACH

#endif