#ifndef C23META_LIST_LENGTH
#define C23META_LIST_LENGTH

#define LIST_LENGTH(X) _LIST_LENGTH_EVAL(_LIST_LENGTH(U32_0,LIST_IS_NIL(X),X))
#define _LIST_LENGTH_EVAL(X)  _LIST_LENGTH_EVAL1(_LIST_LENGTH_EVAL1(_LIST_LENGTH_EVAL1(_LIST_LENGTH_EVAL1(X))))
#define _LIST_LENGTH_EVAL1(X) _LIST_LENGTH_EVAL2(_LIST_LENGTH_EVAL2(_LIST_LENGTH_EVAL2(_LIST_LENGTH_EVAL2(X))))
#define _LIST_LENGTH_EVAL2(X) _LIST_LENGTH_EVAL3(_LIST_LENGTH_EVAL3(_LIST_LENGTH_EVAL3(_LIST_LENGTH_EVAL3(X))))
#define _LIST_LENGTH_EVAL3(X) X

#define _LIST_LENGTH(R,N,X) DEFER(CAT(_LIST_LENGTH_X, N))(R,X)
#define _LIST_LENGTH_X1(R,X) R
#define _LIST_LENGTH_X0(R,X) _LIST_LENGTH_Y(U32_ADD(R,U32_1),LIST_REST(X))
#define _LIST_LENGTH_Y(R,X) DEFER(_LIST_LENGTH_I)()(R,LIST_IS_NIL(X),X)
#define _LIST_LENGTH_I() _LIST_LENGTH

#endif