#ifndef C23META_LIST_NONE
#define C23META_LIST_NONE

#define LIST_NONE(P,X) _LIST_NONE_C(P,X)
#define _LIST_NONE_C(P,X) _LIST_NONE_EVAL(_LIST_NONE(P,LIST_IS_NIL(X),X))
#define _LIST_NONE_EVAL(X)  _LIST_NONE_EVAL1(_LIST_NONE_EVAL1(_LIST_NONE_EVAL1(_LIST_NONE_EVAL1(X))))
#define _LIST_NONE_EVAL1(X) _LIST_NONE_EVAL2(_LIST_NONE_EVAL2(_LIST_NONE_EVAL2(_LIST_NONE_EVAL2(X))))
#define _LIST_NONE_EVAL2(X) _LIST_NONE_EVAL3(_LIST_NONE_EVAL3(_LIST_NONE_EVAL3(_LIST_NONE_EVAL3(X))))
#define _LIST_NONE_EVAL3(X) X

#define _LIST_NONE(P,N,X) CAT(_LIST_NONE_X, N)(P,X)
#define _LIST_NONE_X1(P,X) 1
#define _LIST_NONE_X0(P,X) CAT(_LIST_NONE_Y,P(LIST_FIRST(X)))(P,X)
#define _LIST_NONE_Y1(P,X) 0
#define _LIST_NONE_Y0(P,X) _LIST_NONE_Z(P,LIST_REST(X))
#define _LIST_NONE_Z(P,X) DEFER(_LIST_NONE_I)()(P,LIST_IS_NIL(X),X)
#define _LIST_NONE_I() _LIST_NONE

#endif