#ifndef C23META_LIST_PUSH
#define C23META_LIST_PUSH

#define LIST_PUSH(X,E) _LIST_PUSH_C(X,E)
#define _LIST_PUSH_C(X,E) _LIST_PUSH_EVAL(_LIST_PUSH(LIST_IS_NIL(X),X,E))
#define _LIST_PUSH_EVAL(X)  _LIST_PUSH_EVAL1(_LIST_PUSH_EVAL1(_LIST_PUSH_EVAL1(_LIST_PUSH_EVAL1(X))))
#define _LIST_PUSH_EVAL1(X) _LIST_PUSH_EVAL2(_LIST_PUSH_EVAL2(_LIST_PUSH_EVAL2(_LIST_PUSH_EVAL2(X))))
#define _LIST_PUSH_EVAL2(X) _LIST_PUSH_EVAL3(_LIST_PUSH_EVAL3(_LIST_PUSH_EVAL3(_LIST_PUSH_EVAL3(X))))
#define _LIST_PUSH_EVAL3(X) X

#define _LIST_PUSH(N,X,E) CAT(_LIST_PUSH_X, N)(X,E)
#define _LIST_PUSH_X1(X,E) (E, LIST_NIL)
#define _LIST_PUSH_X0(X,E) (LIST_FIRST(X), _LIST_PUSH_E(LIST_REST(X),E))
#define _LIST_PUSH_E(X,E) DEFER(_LIST_PUSH_I)()(LIST_IS_NIL(X),X,E)
#define _LIST_PUSH_I() _LIST_PUSH

#endif