#ifndef C23META_LIST_SPLIT
#define C23META_LIST_SPLIT

#define LIST_SPLIT(P,X) _LIST_SPLIT_EVAL(_LIST_SPLIT(P,LIST_NIL,LIST_IS_NIL(X),X))
#define _LIST_SPLIT_EVAL(X)  _LIST_SPLIT_EVAL1(_LIST_SPLIT_EVAL1(_LIST_SPLIT_EVAL1(_LIST_SPLIT_EVAL1(X))))
#define _LIST_SPLIT_EVAL1(X) _LIST_SPLIT_EVAL2(_LIST_SPLIT_EVAL2(_LIST_SPLIT_EVAL2(_LIST_SPLIT_EVAL2(X))))
#define _LIST_SPLIT_EVAL2(X) _LIST_SPLIT_EVAL3(_LIST_SPLIT_EVAL3(_LIST_SPLIT_EVAL3(_LIST_SPLIT_EVAL3(X))))
#define _LIST_SPLIT_EVAL3(X) X

#define _LIST_SPLIT(P,R,N,X) DEFER(CAT(_LIST_SPLIT_X, N))(P,R,X)
#define _LIST_SPLIT_X1(P,R,X) LIST(LIST_REVERSE(R),LIST_NIL)
#define _LIST_SPLIT_X0(P,R,X) DEFER(CAT(_LIST_SPLIT_Y,P(LIST_FIRST(X))))(P,R,X)
#define _LIST_SPLIT_Y1(P,R,X) LIST(LIST_REVERSE(R),LIST_REST(X))
#define _LIST_SPLIT_Y0(P,R,X) _LIST_SPLIT_Z(P,(LIST_FIRST(X),R),LIST_REST(X))
#define _LIST_SPLIT_Z(P,R,X) DEFER(_LIST_SPLIT_I)()(P,R,LIST_IS_NIL(X),X)
#define _LIST_SPLIT_I() _LIST_SPLIT

#endif