#ifndef C23META_LIST_TAKE_NTH
#define C23META_LIST_TAKE_NTH

#define LIST_TAKE_NTH(X,N) _LIST_TAKE_NTH_C(X,N)
#define _LIST_TAKE_NTH_C(X,N)  _LIST_TAKE_NTH_EVAL(_LIST_TAKE_NTH_PREAMBLE(U32H_EQ(N,U32H_0),X,N))
#define _LIST_TAKE_NTH_EVAL(X)  _LIST_TAKE_NTH_EVAL1(_LIST_TAKE_NTH_EVAL1(_LIST_TAKE_NTH_EVAL1(_LIST_TAKE_NTH_EVAL1(X))))
#define _LIST_TAKE_NTH_EVAL1(X) _LIST_TAKE_NTH_EVAL2(_LIST_TAKE_NTH_EVAL2(_LIST_TAKE_NTH_EVAL2(_LIST_TAKE_NTH_EVAL2(X))))
#define _LIST_TAKE_NTH_EVAL2(X) _LIST_TAKE_NTH_EVAL3(_LIST_TAKE_NTH_EVAL3(_LIST_TAKE_NTH_EVAL3(_LIST_TAKE_NTH_EVAL3(X))))
#define _LIST_TAKE_NTH_EVAL3(X) X

#define _LIST_TAKE_NTH_PREAMBLE(G,X,N) CAT(_LIST_TAKE_NTH_P, G)(X,N)
#define _LIST_TAKE_NTH_P0(X,N)  _LIST_TAKE_NTH(LIST_IS_NIL(X),X,N,N)
#define _LIST_TAKE_NTH_P1(X,N)  LIST_NIL

#define _LIST_TAKE_NTH(NX,X,N0,N) CAT(_LIST_TAKE_NTH_X, NX)(X,N0,N)
#define _LIST_TAKE_NTH_X1(X,N0,N) LIST_NIL
#define _LIST_TAKE_NTH_X0(X,N0,N) CAT(_LIST_TAKE_NTH_Y,U32H_EQ(N,U32H_1))(X,N0,N)
#define _LIST_TAKE_NTH_Y1(X,N0,N) (LIST_FIRST(X),_LIST_TAKE_NTH_Z(LIST_REST(X),N0,N0))
#define _LIST_TAKE_NTH_Y0(X,N0,N) _LIST_TAKE_NTH_Z(LIST_REST(X),N0,U32H_SUB(N,U32H_1))
#define _LIST_TAKE_NTH_Z(X,N0,N) DEFER(_LIST_TAKE_NTH_I)()(LIST_IS_NIL(X),X,N0,N)
#define _LIST_TAKE_NTH_I() _LIST_TAKE_NTH

#endif