#ifndef C23META_LIST_TAKE
#define C23META_LIST_TAKE

#define LIST_TAKE(X,N) _LIST_TAKE_EVAL(_LIST_TAKE(LIST_IS_NIL(X),X,N))
#define _LIST_TAKE_EVAL(X)  _LIST_TAKE_EVAL1(_LIST_TAKE_EVAL1(_LIST_TAKE_EVAL1(_LIST_TAKE_EVAL1(X))))
#define _LIST_TAKE_EVAL1(X) _LIST_TAKE_EVAL2(_LIST_TAKE_EVAL2(_LIST_TAKE_EVAL2(_LIST_TAKE_EVAL2(X))))
#define _LIST_TAKE_EVAL2(X) _LIST_TAKE_EVAL3(_LIST_TAKE_EVAL3(_LIST_TAKE_EVAL3(_LIST_TAKE_EVAL3(X))))
#define _LIST_TAKE_EVAL3(X) X

#define _LIST_TAKE(NX,X,N) DEFER(CAT(_LIST_TAKE_X, NX))(X,N)
#define _LIST_TAKE_X1(X,N) LIST_NIL
#define _LIST_TAKE_X0(X,N) DEFER(CAT(_LIST_TAKE_Y,U32_EQ(N,U32_0)))(X,N)
#define _LIST_TAKE_Y1(X,N) LIST_NIL
#define _LIST_TAKE_Y0(X,N) (LIST_FIRST(X),_LIST_TAKE_Z(LIST_REST(X),U32_SUB(N,U32_1)))
#define _LIST_TAKE_Z(X,N) DEFER(_LIST_TAKE_I)()(LIST_IS_NIL(X),X,N)
#define _LIST_TAKE_I() _LIST_TAKE

#endif