#ifndef C23META_LIST_TAKE_WHILE
#define C23META_LIST_TAKE_WHILE

#define LIST_TAKE_WHILE(P,X) _LIST_TAKE_WHILE_C(P,X)
#define _LIST_TAKE_WHILE_C(P,X) _LIST_TAKE_WHILE_EVAL(_LIST_TAKE_WHILE(P,LIST_IS_NIL(X),X))
#define _LIST_TAKE_WHILE_EVAL(X)  _LIST_TAKE_WHILE_EVAL1(_LIST_TAKE_WHILE_EVAL1(_LIST_TAKE_WHILE_EVAL1(_LIST_TAKE_WHILE_EVAL1(X))))
#define _LIST_TAKE_WHILE_EVAL1(X) _LIST_TAKE_WHILE_EVAL2(_LIST_TAKE_WHILE_EVAL2(_LIST_TAKE_WHILE_EVAL2(_LIST_TAKE_WHILE_EVAL2(X))))
#define _LIST_TAKE_WHILE_EVAL2(X) _LIST_TAKE_WHILE_EVAL3(_LIST_TAKE_WHILE_EVAL3(_LIST_TAKE_WHILE_EVAL3(_LIST_TAKE_WHILE_EVAL3(X))))
#define _LIST_TAKE_WHILE_EVAL3(X) X

#define _LIST_TAKE_WHILE(P,N,X) CAT(_LIST_TAKE_WHILE_X, N)(P,X)
#define _LIST_TAKE_WHILE_X1(P,X) LIST_NIL
#define _LIST_TAKE_WHILE_X0(P,X) CAT(_LIST_TAKE_WHILE_Y,P(LIST_FIRST(X)))(P,X)
#define _LIST_TAKE_WHILE_Y1(P,X) (LIST_FIRST(X),_LIST_TAKE_WHILE_Z(P,LIST_REST(X)))
#define _LIST_TAKE_WHILE_Y0(P,X) LIST_NIL
#define _LIST_TAKE_WHILE_Z(P,X) DEFER(_LIST_TAKE_WHILE_I)()(P,LIST_IS_NIL(X),X)
#define _LIST_TAKE_WHILE_I() _LIST_TAKE_WHILE

#endif