#ifndef C23META_LIST_WALK
#define C23META_LIST_WALK

#define LIST_WALK(F,X) _LIST_WALK_EVAL(_LIST_WALK(F,X))
#define _LIST_WALK_EVAL(X)  _LIST_WALK_EVAL1(_LIST_WALK_EVAL1(_LIST_WALK_EVAL1(_LIST_WALK_EVAL1(X))))
#define _LIST_WALK_EVAL1(X) _LIST_WALK_EVAL2(_LIST_WALK_EVAL2(_LIST_WALK_EVAL2(_LIST_WALK_EVAL2(X))))
#define _LIST_WALK_EVAL2(X) _LIST_WALK_EVAL3(_LIST_WALK_EVAL3(_LIST_WALK_EVAL3(_LIST_WALK_EVAL3(X))))
#define _LIST_WALK_EVAL3(X) X

#define _LIST_WALK(F,X) CAT(_LIST_WALK_X,LIST_IS_NIL(X))(F,X)
#define _LIST_WALK_X1(F,X) LIST_NIL
#define _LIST_WALK_X0(F,X) CAT(_LIST_WALK_Y,IS_LIST(LIST_FIRST(X)))(F,X)
#define _LIST_WALK_Y1(F,X) (DEFER(_LIST_WALK_I)()(F,LIST_FIRST(X)),DEFER(_LIST_WALK_I)()(F,LIST_REST(X)))
#define _LIST_WALK_Y0(F,X) (F(LIST_FIRST(X)),DEFER(_LIST_WALK_I)()(F,LIST_REST(X)))
#define _LIST_WALK_I() _LIST_WALK

#endif