#ifndef C23META_U8H_PRINT
#define C23META_U8H_PRINT

#define U8H_PRINT(X) _U8H_PRINT_C(X)
#define _U8H_PRINT_C(X) _U8H_PRINT_CAT(_U8H_PRINT_EVAL((_U8H_PRINT(U8H_GT(X,U8H_9),X))))
#define _U8H_PRINT_EVAL(X) _U8H_PRINT_EVAL1(_U8H_PRINT_EVAL1(_U8H_PRINT_EVAL1(_U8H_PRINT_EVAL1(X))))
#define _U8H_PRINT_EVAL1(X) _U8H_PRINT_EVAL2(_U8H_PRINT_EVAL2(_U8H_PRINT_EVAL2(_U8H_PRINT_EVAL2(X))))
#define _U8H_PRINT_EVAL2(X) X
#define _U8H_PRINT_CAT(X) _U8H_PRINT_EVAL(CAT_ALL X)

#define _U8H_PRINT(G,X) CAT(_U8H_PRINT_X,G)(U8H_DIV(X,U8H_10)) U8H_PRINT_DIGIT(U8H_REM(X,U8H_10))
#define _U8H_PRINT_X0(X)
#define _U8H_PRINT_X1(X) DEFER(_U8H_PRINT_I)()(U8H_GT(X,U8H_9),X),
#define _U8H_PRINT_I() _U8H_PRINT

#define U8H_PRINT_DIGIT(X) _U8H_PRINT_DIGIT(CAT_ALL X)
#define _U8H_PRINT_DIGIT(X) CAT(_U8H_PRINT_DIGIT_X,X)
#define _U8H_PRINT_DIGIT_X00 0
#define _U8H_PRINT_DIGIT_X10 1
#define _U8H_PRINT_DIGIT_X20 2
#define _U8H_PRINT_DIGIT_X30 3
#define _U8H_PRINT_DIGIT_X40 4
#define _U8H_PRINT_DIGIT_X50 5
#define _U8H_PRINT_DIGIT_X60 6
#define _U8H_PRINT_DIGIT_X70 7
#define _U8H_PRINT_DIGIT_X80 8
#define _U8H_PRINT_DIGIT_X90 9

#endif