#ifndef C23META_FP32H_ADD
#define C23META_FP32H_ADD
#include "../bits/sign.h"
#include "../bits/normalize.h"

#define FP32H_ADD(X,Y) _FP32H_ADD_C(X,Y)
#define _FP32H_ADD_C(X,Y) CAT_ALL(_FP32H_ADD_CHECK_, FP32H_CLASSIFY(X), _, FP32H_CLASSIFY(Y))(X,Y)

#define _FP32H_ADD_CHECK_nan_nan(X,Y) FP32H_NAN
#define _FP32H_ADD_CHECK_other_nan(X,Y) FP32H_NAN
#define _FP32H_ADD_CHECK_zero_nan(X,Y) FP32H_NAN
#define _FP32H_ADD_CHECK_infinity_nan(X,Y) FP32H_NAN
#define _FP32H_ADD_CHECK_nan_other(X,Y) FP32H_NAN
#define _FP32H_ADD_CHECK_nan_zero(X,Y) FP32H_NAN
#define _FP32H_ADD_CHECK_nan_infinity(X,Y) FP32H_NAN

#define _FP32H_ADD_CHECK_infinity_infinity(X,Y) FP32H_INF
#define _FP32H_ADD_CHECK_infinity_other(X,Y) FP32H_INF
#define _FP32H_ADD_CHECK_infinity_zero(X,Y) FP32H_INF
#define _FP32H_ADD_CHECK_other_infinity(X,Y) FP32H_INF
#define _FP32H_ADD_CHECK_zero_infinity(X,Y) FP32H_INF

#define _FP32H_ADD_CHECK_other_other(X,Y) FP32H_ADD_UNCHECKED(X,Y)
#define _FP32H_ADD_CHECK_other_zero(X,Y) X
#define _FP32H_ADD_CHECK_zero_other(X,Y) Y

#define _FP32H_ADD_CHECK_zero_zero(X,Y) FP32H_0

#define FP32H_ADD_UNCHECKED(X,Y) FP32H_ADD_EVAL(_FP32H_ADD(FP32H_EXPONENT(X), FP32H_EXPONENT(Y), X, Y))
#define FP32H_ADD_EVAL(X) FP32H_ADD_EVAL1(FP32H_ADD_EVAL1(FP32H_ADD_EVAL1(FP32H_ADD_EVAL1(X))))
#define FP32H_ADD_EVAL1(X) FP32H_ADD_EVAL2(FP32H_ADD_EVAL2(FP32H_ADD_EVAL2(FP32H_ADD_EVAL2(X))))
#define FP32H_ADD_EVAL2(X) X

#define _FP32H_ADD(EX,EY,X,Y) _FP32H_ADD_CMP_EXPS(I32H_GEQ(EX,EY),EX,EY,X,Y)
#define _FP32H_ADD_CMP_EXPS(G,EX,EY,X,Y) CAT(_FP32H_ADD_CMP_EXPS_X,G)(EX,EY,X,Y)
#define _FP32H_ADD_CMP_EXPS_X0(EX,EY,X,Y) _FP32H_ADD_CMP_SIGNS(FP32H_CMP_SIGN(X,Y),EX,EY,X,Y)
#define _FP32H_ADD_CMP_EXPS_X1(EX,EY,X,Y) _FP32H_ADD_CMP_SIGNS(FP32H_CMP_SIGN(X,Y),EY,EX,Y,X)

#define _FP32H_ADD_CMP_SIGNS(S,EX,EY,X,Y) CAT(CAT(_FP32H_ADD_CMP_SIGNS_,S),FP32H_GT_UNCHECKED(X,Y))(EY,EX,Y,X)
#define _FP32H_ADD_CMP_SIGNS_POS_POS0(EX,EY,X,Y) _FP32H_ADD_EQ_EXPS(ADD,EX,EY,X,Y)
#define _FP32H_ADD_CMP_SIGNS_POS_POS1(EX,EY,X,Y) _FP32H_ADD_EQ_EXPS(ADD,EX,EY,X,Y)
#define _FP32H_ADD_CMP_SIGNS_POS_NEG0(EX,EY,X,Y) _FP32H_ADD_EQ_EXPS(SUB,EX,EY,X,Y)
#define _FP32H_ADD_CMP_SIGNS_POS_NEG1(EX,EY,X,Y) FP32H_NEG(_FP32H_ADD_EQ_EXPS(SUB,EX,EY,X,Y))
#define _FP32H_ADD_CMP_SIGNS_NEG_POS0(EX,EY,X,Y) _FP32H_ADD_EQ_EXPS(SUB,EX,EY,X,Y)
#define _FP32H_ADD_CMP_SIGNS_NEG_POS1(EX,EY,X,Y) FP32H_NEG(_FP32H_ADD_EQ_EXPS(SUB,EX,EY,X,Y))
#define _FP32H_ADD_CMP_SIGNS_NEG_NEG0(EX,EY,X,Y) FP32H_NEG(_FP32H_ADD_EQ_EXPS(ADD,EX,EY,X,Y))
#define _FP32H_ADD_CMP_SIGNS_NEG_NEG1(EX,EY,X,Y) FP32H_NEG(_FP32H_ADD_EQ_EXPS(ADD,EX,EY,X,Y))

#define _FP32H_ADD_EQ_EXPS(A,EX,EY,X,Y) _FP32H_ADD_EQ_EXPS_X(A,U32H_SUB(EX,EY),EX,FP32H_MANTISSA(X),FP32H_MANTISSA(Y))
#define _FP32H_ADD_EQ_EXPS_X(A,EZ,EX,MX,MY) _FP32H_ADD_EQ_EXPS_Y(A,U32H_GT(EZ,U32H_23),EZ,EX,MX,MY)
#define _FP32H_ADD_EQ_EXPS_Y(A,G,EZ,EX,MX,MY) CAT(_FP32H_ADD_EQ_EXPS_Z,G)(A,EZ,EX,MX,MY)
#define _FP32H_ADD_EQ_EXPS_Z0(A,EZ,EX,MX,MY) _FP32H_ADD_EQ_EXPS_W(A,EX,MX,U32H_RSH(MY,EZ))
#define _FP32H_ADD_EQ_EXPS_Z1(A,EZ,EX,MX,MY) _FP32H_ADD_EQ_EXPS_W(A,EX,MX,U32H_RSH(MY,EZ))
#define _FP32H_ADD_EQ_EXPS_W(A,EX,MX,MY) CAT(_FP32H_ADD_MAIN_,A)(EX,MX,MY)

#define _FP32H_ADD_MAIN_ADD(E,MX,MY) FP32H_NORMALIZE(E,U32H_ADD(MX,MY))
#define _FP32H_ADD_MAIN_SUB(E,MX,MY) _FP32H_ADD_MAIN_SUB_X(E,U32H_GT(MX,MY),MX,MY)
#define _FP32H_ADD_MAIN_SUB_X(E,G,MX,MY) CAT(_FP32H_ADD_MAIN_SUB_Y,G)(E,MX,MY)
#define _FP32H_ADD_MAIN_SUB_Y1(E,MX,MY) FP32H_NORMALIZE(E,U32H_SUB(MX,MY))
#define _FP32H_ADD_MAIN_SUB_Y0(E,MX,MY) FP32H_NEG(FP32H_NORMALIZE(E,U32H_SUB(MY,MX)))

#endif