#ifndef C23META_FP32H_LOG
#define C23META_FP32H_LOG

#define FP32H_LOG(X,Y) _FP32H_LOG_C(X,Y)
#define _FP32H_LOG_C(X,Y) CAT(_FP32H_LOG_CHECK_, FP32H_CMP_SIGN(X,Y))(X,Y)

#define _FP32H_LOG_CHECK_NAN_NAN(X,Y) FP32H_NAN
#define _FP32H_LOG_CHECK_OTHER_NAN(X,Y) FP32H_NAN
#define _FP32H_LOG_CHECK_ZERO_NAN(X,Y) FP32H_NAN
#define _FP32H_LOG_CHECK_INFINITY_NAN(X,Y) FP32H_NAN
#define _FP32H_LOG_CHECK_NAN_OTHER(X,Y) FP32H_NAN
#define _FP32H_LOG_CHECK_NAN_ZERO(X,Y) FP32H_NAN
#define _FP32H_LOG_CHECK_NAN_INFINITY(X,Y) FP32H_NAN

#define _FP32H_LOG_CHECK_INFINITY_INFINITY(X,Y) FP32H_NAN
#define _FP32H_LOG_CHECK_INFINITY_OTHER(X,Y) FP32H_0
#define _FP32H_LOG_CHECK_INFINITY_ZERO(X,Y) FP32H_NAN
#define _FP32H_LOG_CHECK_OTHER_INFINITY(X,Y) FP32H_INF
#define _FP32H_LOG_CHECK_ZERO_INFINITY(X,Y) FP32H_NAN

#define _FP32H_LOG_CHECK_OTHER_OTHER(X,Y) FP32H_LOG_UNCHECKED(X,Y)
#define _FP32H_LOG_CHECK_OTHER_ZERO(X,Y) FP32H_NINF
#define _FP32H_LOG_CHECK_ZERO_OTHER(X,Y) FP32H_N0

#define _FP32H_LOG_CHECK_ZERO_ZERO(X,Y) FP32H_NAN

#define _FP32H_LOG_CHECK_POS_POS(X,Y) CAT_ALL(_FP32H_LOG_CHECK_, FP32H_CLASSIFY(X), _, FP32H_CLASSIFY(Y))(X,Y)
#define _FP32H_LOG_CHECK_POS_NEG(X) FP32H_NAN
#define _FP32H_LOG_CHECK_NEG_POS(X) FP32H_NAN
#define _FP32H_LOG_CHECK_NEG_NEG(X) FP32H_NAN

#define FP32H_LOG_UNCHECKED(X,B) FP32H_DIV_UNCHECKED(FP32H_LOG2_UNCHECKED(X), FP32H_LOG2_UNCHECKED(B))

#endif