#ifndef C23META_FP32H_MIN
#define C23META_FP32H_MIN

#define FP32H_MIN(X,Y) _FP32H_MIN_C(X,Y)
#define _FP32H_MIN_C(X,Y) CAT_ALL(_FP32H_MIN_CHECK_, FP32H_CLASSIFY(X), _, FP32H_CLASSIFY(Y))(X,Y)

#define _FP32H_MIN_CHECK_NAN_NAN(X,Y) FP32H_NAN
#define _FP32H_MIN_CHECK_OTHER_NAN(X,Y) FP32H_NAN
#define _FP32H_MIN_CHECK_ZERO_NAN(X,Y) FP32H_NAN
#define _FP32H_MIN_CHECK_INFINITY_NAN(X,Y) FP32H_NAN
#define _FP32H_MIN_CHECK_NAN_OTHER(X,Y) FP32H_NAN
#define _FP32H_MIN_CHECK_NAN_ZERO(X,Y) FP32H_NAN
#define _FP32H_MIN_CHECK_NAN_INFINITY(X,Y) FP32H_NAN

#define _FP32H_MIN_CHECK_INFINITY_INFINITY(X,Y) FP32H_MIN_UNCHECKED(X,Y)
#define _FP32H_MIN_CHECK_INFINITY_OTHER(X,Y) FP32H_MIN_UNCHECKED(X,Y)
#define _FP32H_MIN_CHECK_INFINITY_ZERO(X,Y) FP32H_MIN_UNCHECKED(X,Y)
#define _FP32H_MIN_CHECK_OTHER_INFINITY(X,Y) FP32H_MIN_UNCHECKED(X,Y)
#define _FP32H_MIN_CHECK_ZERO_INFINITY(X,Y) FP32H_MIN_UNCHECKED(X,Y)

#define _FP32H_MIN_CHECK_OTHER_OTHER(X,Y) FP32H_MIN_UNCHECKED(X,Y)
#define _FP32H_MIN_CHECK_OTHER_ZERO(X,Y) FP32H_MIN_UNCHECKED(X,Y)
#define _FP32H_MIN_CHECK_ZERO_OTHER(X,Y) FP32H_MIN_UNCHECKED(X,Y)

#define _FP32H_MIN_CHECK_ZERO_ZERO(X,Y) FP32H_0

#define FP32H_MIN_UNCHECKED(X,Y) _FP32H_MIN(FP32H_LT(X,Y),X,Y)
#define _FP32H_MIN(G,X,Y) _FP32H_MIN_X(G,X,Y)
#define _FP32H_MIN_X(G,X,Y) _FP32H_MIN_EVAL(DEFER(_FP32H_MIN_Y ## G)(X,Y))
#define _FP32H_MIN_Y0(X,Y) Y
#define _FP32H_MIN_Y1(X,Y) X
#define _FP32H_MIN_EVAL(X) X

#endif