#ifndef C23META_I32H_CONVERT
#define C23META_I32H_CONVERT

#define I32H_CONVERT(X) _I32H_CONVERT_C(X)
#define _I32H_CONVERT_C(X) I32H_CONVERT_EVAL(_I32H_CONVERT(I32H_SIGN_BIT(X),X))
#define I32H_CONVERT_EVAL(X) X

#define _I32H_CONVERT(S,X) _I32H_CONVERT_X(S,X)
#define _I32H_CONVERT_X(S,X) CAT(_I32H_CONVERT_X,S)(X)
#define _I32H_CONVERT_X0(X) U32H_CONVERT(X)
#define _I32H_CONVERT_X1(X) (-U32H_CONVERT(I32H_NEG(X)))

#endif