#ifndef C23META_TUPLE_AS_ARRAY
#define C23META_TUPLE_AS_ARRAY

#define TUPLE_AS_ARRAY(X,...) _TUPLE_AS_ARRAY_C(X __VA_OPT__(,) __VA_ARGS__)
#define _TUPLE_AS_ARRAY_C(X,...) _TUPLE_AS_ARRAY(TUPLE_LENGTH(X), _TUPLE_AS_ARRAY_TYPE ## __VA_OPT__(1(__VA_ARGS__) IGNORE)(X), X)
#define _TUPLE_AS_ARRAY_EVAL(X) TUPLE_APPLY(_TUPLE_AS_ARRAY, X)
#define _TUPLE_AS_ARRAY(LEN,TYPE,TUP) (TYPE[U32_CONVERT(LEN)]){UNWRAP TUP}

#define _TUPLE_AS_ARRAY_TYPE(X) typeof(TUPLE_FIRST(X))
#define _TUPLE_AS_ARRAY_TYPE1(T) T
#endif