#ifndef C23META_TUPLE_DROP_NTH
#define C23META_TUPLE_DROP_NTH

#define TUPLE_DROP_NTH(X,N) TUPLE_REST(_TUPLE_DROP_NTH_EVAL((_TUPLE_DROP_NTH_PREAMBLE(U32_EQ(N,U32_0),X,N))))
#define _TUPLE_DROP_NTH_EVAL(X)  _TUPLE_DROP_NTH_EVAL1(_TUPLE_DROP_NTH_EVAL1(_TUPLE_DROP_NTH_EVAL1(_TUPLE_DROP_NTH_EVAL1(X))))
#define _TUPLE_DROP_NTH_EVAL1(X) _TUPLE_DROP_NTH_EVAL2(_TUPLE_DROP_NTH_EVAL2(_TUPLE_DROP_NTH_EVAL2(_TUPLE_DROP_NTH_EVAL2(X))))
#define _TUPLE_DROP_NTH_EVAL2(X) _TUPLE_DROP_NTH_EVAL3(_TUPLE_DROP_NTH_EVAL3(_TUPLE_DROP_NTH_EVAL3(_TUPLE_DROP_NTH_EVAL3(X))))
#define _TUPLE_DROP_NTH_EVAL3(X) X

#define _TUPLE_DROP_NTH_PREAMBLE(G,X,N) DEFER(CAT(_TUPLE_DROP_NTH_P, G))(X,N)
#define _TUPLE_DROP_NTH_P0(X,N)  _TUPLE_DROP_NTH(TUPLE_IS_EMPTY(X),X,N,N)
#define _TUPLE_DROP_NTH_P1(X,N)

#define _TUPLE_DROP_NTH(NX,X,N0,N) DEFER(CAT(_TUPLE_DROP_NTH_X, NX))(X,N0,N)
#define _TUPLE_DROP_NTH_X1(X,N0,N)
#define _TUPLE_DROP_NTH_X0(X,N0,N) DEFER(CAT(_TUPLE_DROP_NTH_Y,U32_EQ(N,U32_1)))(X,N0,N)
#define _TUPLE_DROP_NTH_Y1(X,N0,N) _TUPLE_DROP_NTH_Z(TUPLE_REST(X),N0,N0)
#define _TUPLE_DROP_NTH_Y0(X,N0,N) ,TUPLE_FIRST(X)_TUPLE_DROP_NTH_Z(TUPLE_REST(X),N0,U32_SUB(N,U32_1))
#define _TUPLE_DROP_NTH_Z(X,N0,N) DEFER(_TUPLE_DROP_NTH_I)()(TUPLE_IS_EMPTY(X),X,N0,N)
#define _TUPLE_DROP_NTH_I() _TUPLE_DROP_NTH

#endif