#ifndef C23META_TUPLE_DROP
#define C23META_TUPLE_DROP

#define TUPLE_DROP(X,N) _TUPLE_DROP_C(X,N)
#define _TUPLE_DROP_C(X,N) _TUPLE_DROP_EVAL(_TUPLE_DROP(TUPLE_IS_EMPTY(X),X,N))
#define _TUPLE_DROP_EVAL(X)  _TUPLE_DROP_EVAL1(_TUPLE_DROP_EVAL1(_TUPLE_DROP_EVAL1(_TUPLE_DROP_EVAL1(X))))
#define _TUPLE_DROP_EVAL1(X) _TUPLE_DROP_EVAL2(_TUPLE_DROP_EVAL2(_TUPLE_DROP_EVAL2(_TUPLE_DROP_EVAL2(X))))
#define _TUPLE_DROP_EVAL2(X) _TUPLE_DROP_EVAL3(_TUPLE_DROP_EVAL3(_TUPLE_DROP_EVAL3(_TUPLE_DROP_EVAL3(X))))
#define _TUPLE_DROP_EVAL3(X) X

#define _TUPLE_DROP(NX,X,N) CAT(_TUPLE_DROP_X, NX)(X,N)
#define _TUPLE_DROP_X1(X,N) ()
#define _TUPLE_DROP_X0(X,N) CAT(_TUPLE_DROP_Y,U32_EQ(N,U32_0))(X,N)
#define _TUPLE_DROP_Y1(X,N) X
#define _TUPLE_DROP_Y0(X,N) _TUPLE_DROP_Z(TUPLE_REST(X),U32_SUB(N,U32_1))
#define _TUPLE_DROP_Z(X,N) DEFER(_TUPLE_DROP_I)()(TUPLE_IS_EMPTY(X),X,N)
#define _TUPLE_DROP_I() _TUPLE_DROP

#endif