#ifndef C23META_TUPLE_DROP_WHILE
#define C23META_TUPLE_DROP_WHILE

#define TUPLE_DROP_WHILE(P,X) _TUPLE_DROP_WHILE_EVAL(_TUPLE_DROP_WHILE(P,TUPLE_IS_EMPTY(X),X))
#define _TUPLE_DROP_WHILE_EVAL(X)  _TUPLE_DROP_WHILE_EVAL1(_TUPLE_DROP_WHILE_EVAL1(_TUPLE_DROP_WHILE_EVAL1(_TUPLE_DROP_WHILE_EVAL1(X))))
#define _TUPLE_DROP_WHILE_EVAL1(X) _TUPLE_DROP_WHILE_EVAL2(_TUPLE_DROP_WHILE_EVAL2(_TUPLE_DROP_WHILE_EVAL2(_TUPLE_DROP_WHILE_EVAL2(X))))
#define _TUPLE_DROP_WHILE_EVAL2(X) _TUPLE_DROP_WHILE_EVAL3(_TUPLE_DROP_WHILE_EVAL3(_TUPLE_DROP_WHILE_EVAL3(_TUPLE_DROP_WHILE_EVAL3(X))))
#define _TUPLE_DROP_WHILE_EVAL3(X) X

#define _TUPLE_DROP_WHILE(P,N,X) DEFER(CAT(_TUPLE_DROP_WHILE_X, N))(P,X)
#define _TUPLE_DROP_WHILE_X1(P,X)
#define _TUPLE_DROP_WHILE_X0(P,X) DEFER(CAT(_TUPLE_DROP_WHILE_Y,P(TUPLE_FIRST(X))))(P,X)
#define _TUPLE_DROP_WHILE_Y1(P,X) _TUPLE_DROP_WHILE_Z(P,TUPLE_REST(X))
#define _TUPLE_DROP_WHILE_Y0(P,X) X
#define _TUPLE_DROP_WHILE_Z(P,X) DEFER(_TUPLE_DROP_WHILE_I)()(P,TUPLE_IS_EMPTY(X),X)
#define _TUPLE_DROP_WHILE_I() _TUPLE_DROP_WHILE

#endif