#ifndef C23META_TUPLE_DROP_LAST
#define C23META_TUPLE_DROP_LAST

#define TUPLE_DROP_LAST(X,N) _TUPLE_DROP_LAST_C(X,N)
#define _TUPLE_DROP_LAST_C(X,N) _TUPLE_DROP_LAST_EVAL(_TUPLE_DROP_LAST(X, TUPLE_LENGTH(X), N))
#define _TUPLE_DROP_LAST_EVAL(X) X
#define _TUPLE_DROP_LAST(X,LEN,N) CAT(_TUPLE_DROP_LAST_X,U32_GEQ(LEN,N))(X,LEN,N)
#define _TUPLE_DROP_LAST_X1(X,LEN,N) TUPLE_TAKE(X,U32_SUB(LEN,N))
#define _TUPLE_DROP_LAST_X0(X,LEN,N) ()

#endif