#ifndef C23META_TUPLE_ENUMERATE
#define C23META_TUPLE_ENUMERATE

#define TUPLE_ENUMERATE(X) _TUPLE_ENUMERATE_C(X)
#define _TUPLE_ENUMERATE_C(X) TUPLE_REST(_TUPLE_ENUMERATE_EVAL((_TUPLE_ENUMERATE(TUPLE_IS_EMPTY(X),X,U32H_0))))
#define _TUPLE_ENUMERATE_EVAL(X)  _TUPLE_ENUMERATE_EVAL1(_TUPLE_ENUMERATE_EVAL1(_TUPLE_ENUMERATE_EVAL1(_TUPLE_ENUMERATE_EVAL1(X))))
#define _TUPLE_ENUMERATE_EVAL1(X) _TUPLE_ENUMERATE_EVAL2(_TUPLE_ENUMERATE_EVAL2(_TUPLE_ENUMERATE_EVAL2(_TUPLE_ENUMERATE_EVAL2(X))))
#define _TUPLE_ENUMERATE_EVAL2(X) _TUPLE_ENUMERATE_EVAL3(_TUPLE_ENUMERATE_EVAL3(_TUPLE_ENUMERATE_EVAL3(_TUPLE_ENUMERATE_EVAL3(X))))
#define _TUPLE_ENUMERATE_EVAL3(X) X

#define _TUPLE_ENUMERATE(NX,X,N) CAT(_TUPLE_ENUMERATE_X, NX)(X,N)
#define _TUPLE_ENUMERATE_X1(X,N)
#define _TUPLE_ENUMERATE_X0(X,N) ,(N,TUPLE_FIRST(X))_TUPLE_ENUMERATE_Y(TUPLE_REST(X),U32H_ADD(N,U32H_1))
#define _TUPLE_ENUMERATE_Y(X,N) DEFER(_TUPLE_ENUMERATE_I)()(TUPLE_IS_EMPTY(X),X,N)
#define _TUPLE_ENUMERATE_I() _TUPLE_ENUMERATE

#endif