#ifndef C23META_TUPLE_EVERY
#define C23META_TUPLE_EVERY

#define TUPLE_EVERY(P,X) _TUPLE_EVERY_EVAL(_TUPLE_EVERY(P,TUPLE_IS_EMPTY(X),X))
#define _TUPLE_EVERY_EVAL(X)  _TUPLE_EVERY_EVAL1(_TUPLE_EVERY_EVAL1(_TUPLE_EVERY_EVAL1(_TUPLE_EVERY_EVAL1(X))))
#define _TUPLE_EVERY_EVAL1(X) _TUPLE_EVERY_EVAL2(_TUPLE_EVERY_EVAL2(_TUPLE_EVERY_EVAL2(_TUPLE_EVERY_EVAL2(X))))
#define _TUPLE_EVERY_EVAL2(X) _TUPLE_EVERY_EVAL3(_TUPLE_EVERY_EVAL3(_TUPLE_EVERY_EVAL3(_TUPLE_EVERY_EVAL3(X))))
#define _TUPLE_EVERY_EVAL3(X) X

#define _TUPLE_EVERY(P,N,X) DEFER(CAT(_TUPLE_EVERY_X, N))(P,X)
#define _TUPLE_EVERY_X1(P,X) 1
#define _TUPLE_EVERY_X0(P,X) DEFER(CAT(_TUPLE_EVERY_Y,P(TUPLE_FIRST(X))))(P,X)
#define _TUPLE_EVERY_Y1(P,X) _TUPLE_EVERY_Z(P,TUPLE_REST(X))
#define _TUPLE_EVERY_Y0(P,X) 0
#define _TUPLE_EVERY_Z(P,X) DEFER(_TUPLE_EVERY_I)()(P,TUPLE_IS_EMPTY(X),X)
#define _TUPLE_EVERY_I() _TUPLE_EVERY

#endif