#ifndef C23META_TUPLE_FIND_FIRST
#define C23META_TUPLE_FIND_FIRST

#define TUPLE_FIND_FIRST(P,X) _TUPLE_FIND_FIRST_C(P,X)
#define _TUPLE_FIND_FIRST_C(P,X) _TUPLE_FIND_FIRST_EVAL(_TUPLE_FIND_FIRST(P,TUPLE_IS_EMPTY(X),X))
#define _TUPLE_FIND_FIRST_EVAL(X)  _TUPLE_FIND_FIRST_EVAL1(_TUPLE_FIND_FIRST_EVAL1(_TUPLE_FIND_FIRST_EVAL1(_TUPLE_FIND_FIRST_EVAL1(X))))
#define _TUPLE_FIND_FIRST_EVAL1(X) _TUPLE_FIND_FIRST_EVAL2(_TUPLE_FIND_FIRST_EVAL2(_TUPLE_FIND_FIRST_EVAL2(_TUPLE_FIND_FIRST_EVAL2(X))))
#define _TUPLE_FIND_FIRST_EVAL2(X) _TUPLE_FIND_FIRST_EVAL3(_TUPLE_FIND_FIRST_EVAL3(_TUPLE_FIND_FIRST_EVAL3(_TUPLE_FIND_FIRST_EVAL3(X))))
#define _TUPLE_FIND_FIRST_EVAL3(X) X

#define _TUPLE_FIND_FIRST(P,N,X) CAT(_TUPLE_FIND_FIRST_X, N)(P,X)
#define _TUPLE_FIND_FIRST_X1(P,X) ()
#define _TUPLE_FIND_FIRST_X0(P,X) CAT(_TUPLE_FIND_FIRST_Y,P(TUPLE_FIRST(X)))(P,X)
#define _TUPLE_FIND_FIRST_Y1(P,X) TUPLE_FIRST(X)
#define _TUPLE_FIND_FIRST_Y0(P,X) _TUPLE_FIND_FIRST_Z(P,TUPLE_REST(X))
#define _TUPLE_FIND_FIRST_Z(P,X) DEFER(_TUPLE_FIND_FIRST_I)()(P,TUPLE_IS_EMPTY(X),X)
#define _TUPLE_FIND_FIRST_I() _TUPLE_FIND_FIRST

#endif