#ifndef C23META_TUPLE_FOLDL
#define C23META_TUPLE_FOLDL

#define TUPLE_FOLDL(F,X,...) _TUPLE_FOLDL_EVAL(_TUPLE_FOLDL(F,TUPLE_IS_EMPTY(X),_TUPLE_FOLDL_P ## __VA_OPT__(1)(X),_TUPLE_FOLDL_INIT ## __VA_OPT__(1(__VA_ARGS__) IGNORE) (X)))
#define _TUPLE_FOLDL_EVAL(X)  _TUPLE_FOLDL_EVAL1(_TUPLE_FOLDL_EVAL1(_TUPLE_FOLDL_EVAL1(_TUPLE_FOLDL_EVAL1(X))))
#define _TUPLE_FOLDL_EVAL1(X) _TUPLE_FOLDL_EVAL2(_TUPLE_FOLDL_EVAL2(_TUPLE_FOLDL_EVAL2(_TUPLE_FOLDL_EVAL2(X))))
#define _TUPLE_FOLDL_EVAL2(X) _TUPLE_FOLDL_EVAL3(_TUPLE_FOLDL_EVAL3(_TUPLE_FOLDL_EVAL3(_TUPLE_FOLDL_EVAL3(X))))
#define _TUPLE_FOLDL_EVAL3(X) X

#define _TUPLE_FOLDL_P(X) TUPLE_REST(X)
#define _TUPLE_FOLDL_P1(X) X

#define _TUPLE_FOLDL_INIT(X) TUPLE_FIRST(X)
#define _TUPLE_FOLDL_INIT1(I) I

#define _TUPLE_FOLDL(F,N,X,R) DEFER(CAT(_TUPLE_FOLDL_X, N))(F,X,R)
#define _TUPLE_FOLDL_X1(F,X,R) R
#define _TUPLE_FOLDL_X0(F,X,R) _TUPLE_FOLDL_Y(F,TUPLE_REST(X),F(R,TUPLE_FIRST(X)))
#define _TUPLE_FOLDL_Y(F,X,R) DEFER(_TUPLE_FOLDL_I)()(F,TUPLE_IS_EMPTY(X),X,R)
#define _TUPLE_FOLDL_I() _TUPLE_FOLDL

#endif