#ifndef C23META_TUPLE_INSERT
#define C23META_TUPLE_INSERT

#define TUPLE_INSERT(X,E,N) _TUPLE_INSERT_C(X,E,N)
#define _TUPLE_INSERT_C(X,E,N) TUPLE_REST(_TUPLE_INSERT_EVAL((_TUPLE_INSERT(TUPLE_IS_EMPTY(X),X,E,N))))
#define _TUPLE_INSERT_EVAL(X)  _TUPLE_INSERT_EVAL1(_TUPLE_INSERT_EVAL1(_TUPLE_INSERT_EVAL1(_TUPLE_INSERT_EVAL1(X))))
#define _TUPLE_INSERT_EVAL1(X) _TUPLE_INSERT_EVAL2(_TUPLE_INSERT_EVAL2(_TUPLE_INSERT_EVAL2(_TUPLE_INSERT_EVAL2(X))))
#define _TUPLE_INSERT_EVAL2(X) _TUPLE_INSERT_EVAL3(_TUPLE_INSERT_EVAL3(_TUPLE_INSERT_EVAL3(_TUPLE_INSERT_EVAL3(X))))
#define _TUPLE_INSERT_EVAL3(X) X

#define _TUPLE_INSERT(NX,X,E,N) CAT(_TUPLE_INSERT_X, NX)(X,E,N)
#define _TUPLE_INSERT_X1(X,E,N)
#define _TUPLE_INSERT_X0(X,E,N) CAT(_TUPLE_INSERT_Y,U32H_EQ(N,U32H_0))(X,E,N)
#define _TUPLE_INSERT_Y1(X,E,N) ,UNWRAP(E)UNWRAP(COMMA_IF X)UNWRAP X
#define _TUPLE_INSERT_Y0(X,E,N) ,TUPLE_FIRST(X)_TUPLE_INSERT_Z(TUPLE_REST(X),E,U32H_SUB(N,U32H_1))
#define _TUPLE_INSERT_Z(X,E,N) DEFER(_TUPLE_INSERT_I)()(TUPLE_IS_EMPTY(X),X,E,N)
#define _TUPLE_INSERT_I() _TUPLE_INSERT

#endif