#ifndef C23META_TUPLE_IS_TUPLE
#define C23META_TUPLE_IS_TUPLE

#define IS_TUPLE(X) _TUPLE_IS_TUPLE_EVAL(DEFER(_TUPLE_IS_TUPLE)(_TUPLE_IS_TUPLE_PROBE X))
#define _TUPLE_IS_TUPLE_EVAL(X) _TUPLE_IS_TUPLE_EVAL1(_TUPLE_IS_TUPLE_EVAL1(_TUPLE_IS_TUPLE_EVAL1(_TUPLE_IS_TUPLE_EVAL1(X))))
#define _TUPLE_IS_TUPLE_EVAL1(X) X

#define _TUPLE_IS_TUPLE_PROBE(...) ~,~
#define _TUPLE_IS_TUPLE(X,...) _TUPLE_IS_TUPLE_X ## __VA_OPT__(1)()
#define _TUPLE_IS_TUPLE_X1() 1
#define _TUPLE_IS_TUPLE_X() 0

#endif