#ifndef C23META_TUPLE_LAST
#define C23META_TUPLE_LAST

#define TUPLE_LAST(X) _TUPLE_LAST_EVAL(_TUPLE_LAST X)
#define _TUPLE_LAST_EVAL(X) _TUPLE_LAST_EVAL1(_TUPLE_LAST_EVAL1(_TUPLE_LAST_EVAL1(_TUPLE_LAST_EVAL1(X))))
#define _TUPLE_LAST_EVAL1(X) _TUPLE_LAST_EVAL2(_TUPLE_LAST_EVAL2(_TUPLE_LAST_EVAL2(_TUPLE_LAST_EVAL2(X))))
#define _TUPLE_LAST_EVAL2(X) _TUPLE_LAST_EVAL3(_TUPLE_LAST_EVAL3(_TUPLE_LAST_EVAL3(_TUPLE_LAST_EVAL3(X))))
#define _TUPLE_LAST_EVAL3(X) X

#define _TUPLE_LAST(X,...) _TUPLE_LAST_X ## __VA_OPT__(1(__VA_ARGS__) IGNORE) (X)
#define _TUPLE_LAST_X1(...) DEFER(_TUPLE_LAST_I)()(__VA_ARGS__)
#define _TUPLE_LAST_X(X) X
#define _TUPLE_LAST_I() _TUPLE_LAST

#endif