#ifndef C23META_TUPLE_MAP2
#define C23META_TUPLE_MAP2

#define TUPLE_MAP2(F,X,Y) _TUPLE_MAP2_C(F,X,Y)
#define _TUPLE_MAP2_C(F,X,Y) _TUPLE_MAP2_EVAL((_TUPLE_MAP2(F,TUPLE_IS_EMPTY(X),TUPLE_IS_EMPTY(Y),X,Y)))
#define _TUPLE_MAP2_EVAL(X)  _TUPLE_MAP2_EVAL1(_TUPLE_MAP2_EVAL1(_TUPLE_MAP2_EVAL1(_TUPLE_MAP2_EVAL1(X))))
#define _TUPLE_MAP2_EVAL1(X) _TUPLE_MAP2_EVAL2(_TUPLE_MAP2_EVAL2(_TUPLE_MAP2_EVAL2(_TUPLE_MAP2_EVAL2(X))))
#define _TUPLE_MAP2_EVAL2(X) _TUPLE_MAP2_EVAL3(_TUPLE_MAP2_EVAL3(_TUPLE_MAP2_EVAL3(_TUPLE_MAP2_EVAL3(X))))
#define _TUPLE_MAP2_EVAL3(X) X

#define _TUPLE_MAP2(F,NX,NY,X,Y) CAT(CAT(_TUPLE_MAP2_X,NX),NY)(F,X,Y)
#define _TUPLE_MAP2_X10(F,X,Y)
#define _TUPLE_MAP2_X01(F,X,Y)
#define _TUPLE_MAP2_X11(F,X,Y)
#define _TUPLE_MAP2_X00(F,X,Y) F(TUPLE_FIRST(X),TUPLE_FIRST(Y))_TUPLE_MAP2_COMMA(X,Y)_TUPLE_MAP2_Y(F,TUPLE_REST(X),TUPLE_REST(Y))
#define _TUPLE_MAP2_Y(F,X,Y) DEFER(_TUPLE_MAP2_I)()(F,TUPLE_IS_EMPTY(X),TUPLE_IS_EMPTY(Y),X,Y)
#define _TUPLE_MAP2_COMMA(X,Y) CAT(CAT(_TUPLE_MAP2_COMMA_X,TUPLE_IS_EMPTY(TUPLE_REST(X))),TUPLE_IS_EMPTY(TUPLE_REST(Y)))()
#define _TUPLE_MAP2_COMMA_X10()
#define _TUPLE_MAP2_COMMA_X01()
#define _TUPLE_MAP2_COMMA_X11()
#define _TUPLE_MAP2_COMMA_X00() ,
#define _TUPLE_MAP2_I() _TUPLE_MAP2

#endif