#ifndef C23META_TUPLE_NTH
#define C23META_TUPLE_NTH

#define TUPLE_NTH(X,N) _TUPLE_NTH_C(X,N)
#define _TUPLE_NTH_C(X,N) _TUPLE_NTH_EVAL(DEFER(_TUPLE_NTH) (N COMMA_IF X UNWRAP X))
#define _TUPLE_NTH_EVAL(X) _TUPLE_NTH_EVAL1(_TUPLE_NTH_EVAL1(_TUPLE_NTH_EVAL1(_TUPLE_NTH_EVAL1(X))))
#define _TUPLE_NTH_EVAL1(X) _TUPLE_NTH_EVAL2(_TUPLE_NTH_EVAL2(_TUPLE_NTH_EVAL2(_TUPLE_NTH_EVAL2(X))))
#define _TUPLE_NTH_EVAL2(X) _TUPLE_NTH_EVAL3(_TUPLE_NTH_EVAL3(_TUPLE_NTH_EVAL3(_TUPLE_NTH_EVAL3(X))))
#define _TUPLE_NTH_EVAL3(X) X

#define _TUPLE_NTH(N,...) CAT(_TUPLE_NTH_X, U32H_EQ(N,U32H_0))(N __VA_OPT__(,) __VA_ARGS__)
#define _TUPLE_NTH_X1(N,X,...) X
#define _TUPLE_NTH_X0(N,X,...) DEFER(_TUPLE_NTH_I)()(U32H_SUB(N,U32H_1) __VA_OPT__(,) __VA_ARGS__)
#define _TUPLE_NTH_I() _TUPLE_NTH

#endif