#ifndef C23META_TUPLE_PUSH_FIRST
#define C23META_TUPLE_PUSH_FIRST

#define TUPLE_PUSH_FIRST(X,E) _TUPLE_PUSH_FIRST_C(X,E)
#define _TUPLE_PUSH_FIRST_C(X,E) (UNWRAP(E)UNWRAP(COMMA_IF X)UNWRAP X)

#endif