#ifndef C23META_TUPLE_REMOVE
#define C23META_TUPLE_REMOVE

#define TUPLE_REMOVE(P,X) _TUPLE_REMOVE_C(P,X)
#define _TUPLE_REMOVE_C(P,X) TUPLE_REST(_TUPLE_REMOVE_EVAL((_TUPLE_REMOVE(P,TUPLE_IS_EMPTY(X),X))))
#define _TUPLE_REMOVE_EVAL(X)  _TUPLE_REMOVE_EVAL1(_TUPLE_REMOVE_EVAL1(_TUPLE_REMOVE_EVAL1(_TUPLE_REMOVE_EVAL1(X))))
#define _TUPLE_REMOVE_EVAL1(X) _TUPLE_REMOVE_EVAL2(_TUPLE_REMOVE_EVAL2(_TUPLE_REMOVE_EVAL2(_TUPLE_REMOVE_EVAL2(X))))
#define _TUPLE_REMOVE_EVAL2(X) _TUPLE_REMOVE_EVAL3(_TUPLE_REMOVE_EVAL3(_TUPLE_REMOVE_EVAL3(_TUPLE_REMOVE_EVAL3(X))))
#define _TUPLE_REMOVE_EVAL3(X) X

#define _TUPLE_REMOVE(P,N,X) CAT(_TUPLE_REMOVE_X, N)(P,X)
#define _TUPLE_REMOVE_X1(P,X)
#define _TUPLE_REMOVE_X0(P,X) CAT(_TUPLE_REMOVE_Y,P(TUPLE_FIRST(X)))(P,X)
#define _TUPLE_REMOVE_Y1(P,X) _TUPLE_REMOVE_Z(P,TUPLE_REST(X))
#define _TUPLE_REMOVE_Y0(P,X) ,TUPLE_FIRST(X)_TUPLE_REMOVE_Z(P,TUPLE_REST(X))
#define _TUPLE_REMOVE_Z(P,X) DEFER(_TUPLE_REMOVE_I)()(P,TUPLE_IS_EMPTY(X),X)
#define _TUPLE_REMOVE_I() _TUPLE_REMOVE

#endif