#ifndef C23META_TUPLE_SPLIT_ALL
#define C23META_TUPLE_SPLIT_ALL

#define TUPLE_SPLIT_ALL(P,X) _TUPLE_SPLIT_ALL_C(P,X)
#define _TUPLE_SPLIT_ALL_C(P,X) _TUPLE_SPLIT_ALL_EVAL(_TUPLE_SPLIT_ALL(P,(),(),TUPLE_IS_EMPTY(X),X))
#define _TUPLE_SPLIT_ALL_EVAL(X)  _TUPLE_SPLIT_ALL_EVAL1(_TUPLE_SPLIT_ALL_EVAL1(_TUPLE_SPLIT_ALL_EVAL1(_TUPLE_SPLIT_ALL_EVAL1(X))))
#define _TUPLE_SPLIT_ALL_EVAL1(X) _TUPLE_SPLIT_ALL_EVAL2(_TUPLE_SPLIT_ALL_EVAL2(_TUPLE_SPLIT_ALL_EVAL2(_TUPLE_SPLIT_ALL_EVAL2(X))))
#define _TUPLE_SPLIT_ALL_EVAL2(X) _TUPLE_SPLIT_ALL_EVAL3(_TUPLE_SPLIT_ALL_EVAL3(_TUPLE_SPLIT_ALL_EVAL3(_TUPLE_SPLIT_ALL_EVAL3(X))))
#define _TUPLE_SPLIT_ALL_EVAL3(X) X

#define _TUPLE_SPLIT_ALL(P,R,RF,N,X) CAT(_TUPLE_SPLIT_ALL_X, N)(P,R,RF,X)
#define _TUPLE_SPLIT_ALL_X1(P,R,RF,X) TUPLE_PUSH(RF,R)
#define _TUPLE_SPLIT_ALL_X0(P,R,RF,X) CAT(_TUPLE_SPLIT_ALL_Y,P(TUPLE_FIRST(X)))(P,R,RF,X)
#define _TUPLE_SPLIT_ALL_Y1(P,R,RF,X) _TUPLE_SPLIT_ALL_Z(P,(),TUPLE_PUSH(RF,R),TUPLE_REST(X))
#define _TUPLE_SPLIT_ALL_Y0(P,R,RF,X) _TUPLE_SPLIT_ALL_Z(P,TUPLE_PUSH(R,TUPLE_FIRST(X)),RF,TUPLE_REST(X))
#define _TUPLE_SPLIT_ALL_Z(P,R,RF,X) DEFER(_TUPLE_SPLIT_ALL_I)()(P,R,RF,TUPLE_IS_EMPTY(X),X)
#define _TUPLE_SPLIT_ALL_I() _TUPLE_SPLIT_ALL

#endif