#ifndef C23META_TUPLE_SPLIT
#define C23META_TUPLE_SPLIT

#define TUPLE_SPLIT(P,X) _TUPLE_SPLIT_EVAL(_TUPLE_SPLIT(P,(),TUPLE_IS_EMPTY(X),X))
#define _TUPLE_SPLIT_EVAL(X)  _TUPLE_SPLIT_EVAL1(_TUPLE_SPLIT_EVAL1(_TUPLE_SPLIT_EVAL1(_TUPLE_SPLIT_EVAL1(X))))
#define _TUPLE_SPLIT_EVAL1(X) _TUPLE_SPLIT_EVAL2(_TUPLE_SPLIT_EVAL2(_TUPLE_SPLIT_EVAL2(_TUPLE_SPLIT_EVAL2(X))))
#define _TUPLE_SPLIT_EVAL2(X) _TUPLE_SPLIT_EVAL3(_TUPLE_SPLIT_EVAL3(_TUPLE_SPLIT_EVAL3(_TUPLE_SPLIT_EVAL3(X))))
#define _TUPLE_SPLIT_EVAL3(X) X

#define _TUPLE_SPLIT(P,R,N,X) DEFER(CAT(_TUPLE_SPLIT_X, N))(P,R,X)
#define _TUPLE_SPLIT_X1(P,R,X) (R,())
#define _TUPLE_SPLIT_X0(P,R,X) DEFER(CAT(_TUPLE_SPLIT_Y,P(TUPLE_FIRST(X))))(P,R,X)
#define _TUPLE_SPLIT_Y1(P,R,X) (R,TUPLE_REST(X))
#define _TUPLE_SPLIT_Y0(P,R,X) _TUPLE_SPLIT_Z(P,TUPLE_PUSH(R,TUPLE_FIRST(X)),TUPLE_REST(X))
#define _TUPLE_SPLIT_Z(P,R,X) DEFER(_TUPLE_SPLIT_I)()(P,R,TUPLE_IS_EMPTY(X),X)
#define _TUPLE_SPLIT_I() _TUPLE_SPLIT

#endif