#ifndef C23META_TUPLE_TAKE_LAST
#define C23META_TUPLE_TAKE_LAST

#define TUPLE_TAKE_LAST(X,N) _TUPLE_TAKE_LAST_EVAL(_TUPLE_TAKE_LAST(X, TUPLE_LENGTH(X), N))
#define _TUPLE_TAKE_LAST_EVAL(X) X
#define _TUPLE_TAKE_LAST(X,LEN,N) DEFER(CAT(_TUPLE_TAKE_LAST_X,U32_GEQ(LEN,N)))(X,LEN,N)
#define _TUPLE_TAKE_LAST_X1(X,LEN,N) TUPLE_DROP(X,U32_SUB(LEN,N))
#define _TUPLE_TAKE_LAST_X0(X,LEN,N) ()

#endif