#ifndef C23META_TUPLE_TAKE_WHILE
#define C23META_TUPLE_TAKE_WHILE

#define TUPLE_TAKE_WHILE(P,X) _TUPLE_TAKE_WHILE_C(P,X)
#define _TUPLE_TAKE_WHILE_C(P,X) TUPLE_REST(_TUPLE_TAKE_WHILE_EVAL((_TUPLE_TAKE_WHILE(P,TUPLE_IS_EMPTY(X),X))))
#define _TUPLE_TAKE_WHILE_EVAL(X)  _TUPLE_TAKE_WHILE_EVAL1(_TUPLE_TAKE_WHILE_EVAL1(_TUPLE_TAKE_WHILE_EVAL1(_TUPLE_TAKE_WHILE_EVAL1(X))))
#define _TUPLE_TAKE_WHILE_EVAL1(X) _TUPLE_TAKE_WHILE_EVAL2(_TUPLE_TAKE_WHILE_EVAL2(_TUPLE_TAKE_WHILE_EVAL2(_TUPLE_TAKE_WHILE_EVAL2(X))))
#define _TUPLE_TAKE_WHILE_EVAL2(X) _TUPLE_TAKE_WHILE_EVAL3(_TUPLE_TAKE_WHILE_EVAL3(_TUPLE_TAKE_WHILE_EVAL3(_TUPLE_TAKE_WHILE_EVAL3(X))))
#define _TUPLE_TAKE_WHILE_EVAL3(X) X

#define _TUPLE_TAKE_WHILE(P,N,X) CAT(_TUPLE_TAKE_WHILE_X, N)(P,X)
#define _TUPLE_TAKE_WHILE_X1(P,X)
#define _TUPLE_TAKE_WHILE_X0(P,X) CAT(_TUPLE_TAKE_WHILE_Y,P(TUPLE_FIRST(X)))(P,X)
#define _TUPLE_TAKE_WHILE_Y1(P,X) ,TUPLE_FIRST(X)_TUPLE_TAKE_WHILE_Z(P,TUPLE_REST(X))
#define _TUPLE_TAKE_WHILE_Y0(P,X)
#define _TUPLE_TAKE_WHILE_Z(P,X) DEFER(_TUPLE_TAKE_WHILE_I)()(P,TUPLE_IS_EMPTY(X),X)
#define _TUPLE_TAKE_WHILE_I() _TUPLE_TAKE_WHILE

#endif