#ifndef C23META_TUPLE_WALK
#define C23META_TUPLE_WALK


#define TUPLE_WALK(F,X) _TUPLE_WALK_EVAL((DEFER(_TUPLE_WALK)(F COMMA_IF X UNWRAP X)))
#define _TUPLE_WALK_EVAL(X) _TUPLE_WALK_EVAL1(_TUPLE_WALK_EVAL1(_TUPLE_WALK_EVAL1(_TUPLE_WALK_EVAL1(X))))
#define _TUPLE_WALK_EVAL1(X) _TUPLE_WALK_EVAL2(_TUPLE_WALK_EVAL2(_TUPLE_WALK_EVAL2(_TUPLE_WALK_EVAL2(X))))
#define _TUPLE_WALK_EVAL2(X) _TUPLE_WALK_EVAL3(_TUPLE_WALK_EVAL3(_TUPLE_WALK_EVAL3(_TUPLE_WALK_EVAL3(X))))
#define _TUPLE_WALK_EVAL3(X) X

#define _TUPLE_WALK(F,...) _TUPLE_WALK_X ## __VA_OPT__(1(F,__VA_ARGS__))
#define _TUPLE_WALK_X1(F,X,...) DEFER(CAT(_TUPLE_WALK_Y,IS_TUPLE(X)))(F,X __VA_OPT__(,) __VA_ARGS__)
#define _TUPLE_WALK_X
#define _TUPLE_WALK_Y1(F,X,...) (DEFER(_TUPLE_WALK_I)()(F COMMA_IF X UNWRAP X))__VA_OPT__(,)DEFER(_TUPLE_WALK_I)()(F __VA_OPT__(,)__VA_ARGS__)
#define _TUPLE_WALK_Y0(F,X,...) F(X)__VA_OPT__(,)DEFER(_TUPLE_WALK_I)()(F __VA_OPT__(,)__VA_ARGS__)
#define _TUPLE_WALK_I() _TUPLE_WALK

#endif