#ifndef C23META_LIST_EVERY
#define C23META_LIST_EVERY

#define LIST_EVERY(P,X) _LIST_EVERY_EVAL(_LIST_EVERY(P,LIST_IS_NIL(X),X))
#define _LIST_EVERY_EVAL(X)  _LIST_EVERY_EVAL1(_LIST_EVERY_EVAL1(_LIST_EVERY_EVAL1(_LIST_EVERY_EVAL1(X))))
#define _LIST_EVERY_EVAL1(X) _LIST_EVERY_EVAL2(_LIST_EVERY_EVAL2(_LIST_EVERY_EVAL2(_LIST_EVERY_EVAL2(X))))
#define _LIST_EVERY_EVAL2(X) _LIST_EVERY_EVAL3(_LIST_EVERY_EVAL3(_LIST_EVERY_EVAL3(_LIST_EVERY_EVAL3(X))))
#define _LIST_EVERY_EVAL3(X) X

#define _LIST_EVERY(P,N,X) DEFER(CAT(_LIST_EVERY_X, N))(P,X)
#define _LIST_EVERY_X1(P,X) 1
#define _LIST_EVERY_X0(P,X) DEFER(CAT(_LIST_EVERY_Y,P(LIST_FIRST(X))))(P,X)
#define _LIST_EVERY_Y1(P,X) _LIST_EVERY_Z(P,LIST_REST(X))
#define _LIST_EVERY_Y0(P,X) 0
#define _LIST_EVERY_Z(P,X) DEFER(_LIST_EVERY_I)()(P,LIST_IS_NIL(X),X)
#define _LIST_EVERY_I() _LIST_EVERY

#endif