#ifndef C23META_LIST_IS_LIST
#define C23META_LIST_IS_LIST

#define IS_LIST(X) _LIST_IS_LIST_EVAL(DEFER(_LIST_IS_LIST)(_LIST_IS_LIST_PROBE X))
#define _LIST_IS_LIST_EVAL(X) _LIST_IS_LIST_EVAL1(_LIST_IS_LIST_EVAL1(_LIST_IS_LIST_EVAL1(_LIST_IS_LIST_EVAL1(X))))
#define _LIST_IS_LIST_EVAL1(X) _LIST_IS_LIST_EVAL2(_LIST_IS_LIST_EVAL2(_LIST_IS_LIST_EVAL2(_LIST_IS_LIST_EVAL2(X))))
#define _LIST_IS_LIST_EVAL2(X) _LIST_IS_LIST_EVAL3(_LIST_IS_LIST_EVAL3(_LIST_IS_LIST_EVAL3(_LIST_IS_LIST_EVAL3(X))))
#define _LIST_IS_LIST_EVAL3(X) X

#define _LIST_IS_LIST_PROBE(...) (__VA_ARGS__),~
#define _LIST_IS_LIST(X,...) _LIST_IS_LIST_X ## __VA_OPT__(1)(X)
#define _LIST_IS_LIST_X1(X) _LIST_IS_LIST_Y(LIST_IS_NIL(X),X)
#define _LIST_IS_LIST_X(X) 0
#define _LIST_IS_LIST_Y(N,X) DEFER(CAT(_LIST_IS_LIST_Z,N))(X)
#define _LIST_IS_LIST_Z1(X) 1
#define _LIST_IS_LIST_Z0(X) _LIST_IS_LIST_W(LIST_REST(X))
#define _LIST_IS_LIST_W(X) DEFER(_LIST_IS_LIST_I)()(_LIST_IS_LIST_PROBE X)
#define _LIST_IS_LIST_I() _LIST_IS_LIST


#endif