#ifndef C23META_LIST_LAST
#define C23META_LIST_LAST

#define LIST_LAST(X) _LIST_LAST_EVAL(_LIST_LAST(LIST_NIL,LIST_IS_NIL(X),X))
#define _LIST_LAST_EVAL(X)  _LIST_LAST_EVAL1(_LIST_LAST_EVAL1(_LIST_LAST_EVAL1(_LIST_LAST_EVAL1(X))))
#define _LIST_LAST_EVAL1(X) _LIST_LAST_EVAL2(_LIST_LAST_EVAL2(_LIST_LAST_EVAL2(_LIST_LAST_EVAL2(X))))
#define _LIST_LAST_EVAL2(X) _LIST_LAST_EVAL3(_LIST_LAST_EVAL3(_LIST_LAST_EVAL3(_LIST_LAST_EVAL3(X))))
#define _LIST_LAST_EVAL3(X) X

#define _LIST_LAST(R,N,X) DEFER(CAT(_LIST_LAST_X, N))(R,X)
#define _LIST_LAST_X1(R,X) R
#define _LIST_LAST_X0(R,X) _LIST_LAST_Y(LIST_FIRST(X),LIST_REST(X))
#define _LIST_LAST_Y(R,X) DEFER(_LIST_LAST_I)()(R,LIST_IS_NIL(X),X)
#define _LIST_LAST_I() _LIST_LAST

#endif