#ifndef C23META_LIST_MAP
#define C23META_LIST_MAP

#define LIST_MAP(F,X) _LIST_MAP_EVAL(_LIST_MAP(F,LIST_IS_NIL(X),X))
#define _LIST_MAP_EVAL(X)  _LIST_MAP_EVAL1(_LIST_MAP_EVAL1(_LIST_MAP_EVAL1(_LIST_MAP_EVAL1(X))))
#define _LIST_MAP_EVAL1(X) _LIST_MAP_EVAL2(_LIST_MAP_EVAL2(_LIST_MAP_EVAL2(_LIST_MAP_EVAL2(X))))
#define _LIST_MAP_EVAL2(X) _LIST_MAP_EVAL3(_LIST_MAP_EVAL3(_LIST_MAP_EVAL3(_LIST_MAP_EVAL3(X))))
#define _LIST_MAP_EVAL3(X) X

#define _LIST_MAP(F,N,X) DEFER(CAT(_LIST_MAP_X, N))(F,X)
#define _LIST_MAP_X1(F,X) LIST_NIL
#define _LIST_MAP_X0(F,X) (F(LIST_FIRST(X)),_LIST_MAP_Y(F,LIST_REST(X)))
#define _LIST_MAP_Y(F,X) DEFER(_LIST_MAP_I)()(F,LIST_IS_NIL(X),X)
#define _LIST_MAP_I() _LIST_MAP

#endif