#ifndef C23META_U8H_ADD
#define C23META_U8H_ADD

#define U8H_ADD(X,Y) _U8H_ADD(X,Y)
#define _U8H_ADD(X,Y) _U8H_ADD_EVAL(DEFER(_U8H_ADD_X)(UNWRAP X, UNWRAP Y))
#define _U8H_ADD_EVAL(X) _U8H_ADD_EVAL1(_U8H_ADD_EVAL1(_U8H_ADD_EVAL1(_U8H_ADD_EVAL1(X))))
#define _U8H_ADD_EVAL1(X) _U8H_ADD_EVAL2(_U8H_ADD_EVAL2(X))
#define _U8H_ADD_EVAL2(X) X

#define _U8H_ADD_X(A0,A1,B0,B1)\
  (HEXADD(0,A0,B0,A1,B1))

#endif