#ifndef C23META_U8H_AND
#define C23META_U8H_AND

#define U8H_AND(X,Y) _U8H_AND(X,Y)
#define _U8H_AND(X,Y) _U8H_AND_EVAL(DEFER(_U8H_AND_X)(UNWRAP X, UNWRAP Y))
#define _U8H_AND_EVAL(X) _U8H_AND_EVAL1(_U8H_AND_EVAL1(_U8H_AND_EVAL1(_U8H_AND_EVAL1(X))))
#define _U8H_AND_EVAL1(X) _U8H_AND_EVAL2(_U8H_AND_EVAL2(_U8H_AND_EVAL2(_U8H_AND_EVAL2(X))))
#define _U8H_AND_EVAL2(X) _U8H_AND_EVAL3(_U8H_AND_EVAL3(_U8H_AND_EVAL3(_U8H_AND_EVAL3(X))))
#define _U8H_AND_EVAL3(X) X

#define _U8H_AND_X(A0,A1,B0,B1)\
  (HEXAND(A0,B0,A1,B1))

#endif