#ifndef C23META_U8H_LOG
#define C23META_U8H_LOG

#define U8H_LOG(X,B) _U8H_LOG(X,B)
#define _U8H_LOG(X,B) _U8H_LOG_EVAL(_U8H_LOG_PREAMBLE(U8H_EQ(B, U8H_0), X, B))
#define _U8H_LOG_EVAL(X) _U8H_LOG_EVAL1(_U8H_LOG_EVAL1(_U8H_LOG_EVAL1(_U8H_LOG_EVAL1(X))))
#define _U8H_LOG_EVAL1(X) _U8H_LOG_EVAL2(_U8H_LOG_EVAL2(_U8H_LOG_EVAL2(_U8H_LOG_EVAL2(X))))
#define _U8H_LOG_EVAL2(X) _U8H_LOG_EVAL3(_U8H_LOG_EVAL3(_U8H_LOG_EVAL3(_U8H_LOG_EVAL3(X))))
#define _U8H_LOG_EVAL3(X) _U8H_LOG_EVAL4(_U8H_LOG_EVAL4(_U8H_LOG_EVAL4(_U8H_LOG_EVAL4(X))))
#define _U8H_LOG_EVAL4(X) X

#define _U8H_LOG_PREAMBLE(G,X,B) CAT(_U8H_LOG_P,G)(X,B)
#define _U8H_LOG_P0(X,B) _U8H_LOG_X(X,U8H_0,B)
#define _U8H_LOG_P1(X,B) DO_PRAGMA(GCC error "Invalid base for U8H_LOG")

#define _U8H_LOG_X(X,R,B) _U8H_LOG_Y(U8H_GEQ(X,B),X,R,B)
#define _U8H_LOG_Y(G,X,R,B) CAT(_U8H_LOG_Z,G)(X,R,B)
#define _U8H_LOG_Z0(X,R,B) R
#define _U8H_LOG_Z1(X,R,B) DEFER(_U8H_LOG_I)()(U8H_DIV(X,B),U8H_ADD(R,U8H_1),B)
#define _U8H_LOG_I() _U8H_LOG_X

#endif