#ifndef C23META_U8H_SQRT
#define C23META_U8H_SQRT

#define U8H_SQRT(X) _U8H_SQRT(X)
#define _U8H_SQRT(X) _U8H_SQRT_EVAL(_U8H_SQRT_G(X))
#define _U8H_SQRT_EVAL(X) _U8H_SQRT_EVAL1(_U8H_SQRT_EVAL1(_U8H_SQRT_EVAL1(_U8H_SQRT_EVAL1(X))))
#define _U8H_SQRT_EVAL1(X) _U8H_SQRT_EVAL2(_U8H_SQRT_EVAL2(_U8H_SQRT_EVAL2(_U8H_SQRT_EVAL2(X))))
#define _U8H_SQRT_EVAL2(X) _U8H_SQRT_EVAL3(_U8H_SQRT_EVAL3(_U8H_SQRT_EVAL3(_U8H_SQRT_EVAL3(X))))
#define _U8H_SQRT_EVAL3(X) _U8H_SQRT_EVAL4(_U8H_SQRT_EVAL4(_U8H_SQRT_EVAL4(_U8H_SQRT_EVAL4(X))))
#define _U8H_SQRT_EVAL4(X) X

#define _U8H_SQRT_G(S) _U8H_SQRT_PREAMBLE(U8H_GEQ(U8H_1, S), S)
#define _U8H_SQRT_PREAMBLE(G,S) CAT(_U8H_SQRT_P,G)(S)
#define _U8H_SQRT_P0(S) _U8H_SQRT_X(S,U8H_RSH1(S),_U8H_SQRT_UPDATE(S,U8H_RSH1(S)))
#define _U8H_SQRT_P1(S) S

#define _U8H_SQRT_UPDATE(S,X0) U8H_RSH1(U8H_ADD(X0, U8H_DIV(S,X0)))

#define _U8H_SQRT_X(S,X0,X1) _U8H_SQRT_Y(U8H_GT(X0,X1),S,X0,X1)
#define _U8H_SQRT_Y(G,S,X0,X1) CAT(_U8H_SQRT_Z,G)(S,X0,X1)
#define _U8H_SQRT_Z0(S,X0,X1) X0
#define _U8H_SQRT_Z1(S,X0,X1) DEFER(_U8H_SQRT_I)()(S,X1,_U8H_SQRT_UPDATE(S,X1))
#define _U8H_SQRT_I() _U8H_SQRT_X


#endif