#ifndef C23META_U8H_XOR
#define C23META_U8H_XOR

#define U8H_XOR(X,Y) _U8H_XOR(X,Y)
#define _U8H_XOR(X,Y) _U8H_XOR_EVAL(DEFER(_U8H_XOR_X)(UNWRAP X, UNWRAP Y))
#define _U8H_XOR_EVAL(X) _U8H_XOR_EVAL1(_U8H_XOR_EVAL1(_U8H_XOR_EVAL1(_U8H_XOR_EVAL1(X))))
#define _U8H_XOR_EVAL1(X) _U8H_XOR_EVAL2(_U8H_XOR_EVAL2(_U8H_XOR_EVAL2(_U8H_XOR_EVAL2(X))))
#define _U8H_XOR_EVAL2(X) _U8H_XOR_EVAL3(_U8H_XOR_EVAL3(_U8H_XOR_EVAL3(_U8H_XOR_EVAL3(X))))
#define _U8H_XOR_EVAL3(X) X

#define _U8H_XOR_X(A0,A1,B0,B1)\
  (HEXXOR(A0,B0,A1,B1))

#endif