#ifndef C23META_I8H_CONVERT
#define C23META_I8H_CONVERT

#define I8H_CONVERT(X) _I8H_CONVERT_C(X)
#define _I8H_CONVERT_C(X) I8H_CONVERT_EVAL(_I8H_CONVERT(I8H_SIGN_BIT(X),X))
#define I8H_CONVERT_EVAL(X) X

#define _I8H_CONVERT(S,X) _I8H_CONVERT_X(S,X)
#define _I8H_CONVERT_X(S,X) CAT(_I8H_CONVERT_X,S)(X)
#define _I8H_CONVERT_X0(X) U8H_CONVERT(X)
#define _I8H_CONVERT_X1(X) (-U8H_CONVERT(I8H_NEG(X)))

#endif