#ifndef C23META_FP32_LOG
#define C23META_FP32_LOG

#define FP32_LOG(X,Y) _FP32_LOG_C(X,Y)
#define _FP32_LOG_C(X,Y) CAT(_FP32_LOG_CHECK_, FP32_CMP_SIGN(X,Y))(X,Y)

#define _FP32_LOG_CHECK_NAN_NAN(X,Y) FP32_NAN
#define _FP32_LOG_CHECK_OTHER_NAN(X,Y) FP32_NAN
#define _FP32_LOG_CHECK_ZERO_NAN(X,Y) FP32_NAN
#define _FP32_LOG_CHECK_INFINITY_NAN(X,Y) FP32_NAN
#define _FP32_LOG_CHECK_NAN_OTHER(X,Y) FP32_NAN
#define _FP32_LOG_CHECK_NAN_ZERO(X,Y) FP32_NAN
#define _FP32_LOG_CHECK_NAN_INFINITY(X,Y) FP32_NAN

#define _FP32_LOG_CHECK_INFINITY_INFINITY(X,Y) FP32_NAN
#define _FP32_LOG_CHECK_INFINITY_OTHER(X,Y) FP32_0
#define _FP32_LOG_CHECK_INFINITY_ZERO(X,Y) FP32_NAN
#define _FP32_LOG_CHECK_OTHER_INFINITY(X,Y) FP32_INF
#define _FP32_LOG_CHECK_ZERO_INFINITY(X,Y) FP32_NAN

#define _FP32_LOG_CHECK_OTHER_OTHER(X,Y) FP32_LOG_UNCHECKED(X,Y)
#define _FP32_LOG_CHECK_OTHER_ZERO(X,Y) FP32_NINF
#define _FP32_LOG_CHECK_ZERO_OTHER(X,Y) FP32_N0

#define _FP32_LOG_CHECK_ZERO_ZERO(X,Y) FP32_NAN

#define _FP32_LOG_CHECK_POS_POS(X,Y) CAT_ALL(_FP32_LOG_CHECK_, FP32_CLASSIFY(X), _, FP32_CLASSIFY(Y))(X,Y)
#define _FP32_LOG_CHECK_POS_NEG(X) FP32_NAN
#define _FP32_LOG_CHECK_NEG_POS(X) FP32_NAN
#define _FP32_LOG_CHECK_NEG_NEG(X) FP32_NAN

#define FP32_LOG_UNCHECKED(X,B) FP32_DIV_UNCHECKED(FP32_LOG2_UNCHECKED(X), FP32_LOG2_UNCHECKED(B))

#endif