#ifndef C23META_FP32_MUL
#define C23META_FP32_MUL

#define FP32_MUL(X,Y) CAT_ALL(_FP32_MUL_CHECK_, FP32_CLASSIFY(X), _, FP32_CLASSIFY(Y))(X,Y)

#define _FP32_MUL_CHECK_NAN_NAN(X,Y) FP32_NAN
#define _FP32_MUL_CHECK_OTHER_NAN(X,Y) FP32_NAN
#define _FP32_MUL_CHECK_ZERO_NAN(X,Y) FP32_NAN
#define _FP32_MUL_CHECK_INFINITY_NAN(X,Y) FP32_NAN
#define _FP32_MUL_CHECK_NAN_OTHER(X,Y) FP32_NAN
#define _FP32_MUL_CHECK_NAN_ZERO(X,Y) FP32_NAN
#define _FP32_MUL_CHECK_NAN_INFINITY(X,Y) FP32_NAN

#define _FP32_MUL_CHECK_INFINITY_INFINITY(X,Y) CAT(_FP32_MUL_CHECK_, FP32_CMP_SIGN(X,Y))(FP32_INF)
#define _FP32_MUL_CHECK_INFINITY_OTHER(X,Y) CAT(_FP32_MUL_CHECK_, FP32_CMP_SIGN(X,Y))(FP32_INF)
#define _FP32_MUL_CHECK_INFINITY_ZERO(X,Y) CAT(_FP32_MUL_CHECK_, FP32_CMP_SIGN(X,Y))(FP32_INF)
#define _FP32_MUL_CHECK_OTHER_INFINITY(X,Y) CAT(_FP32_MUL_CHECK_, FP32_CMP_SIGN(X,Y))(FP32_INF)
#define _FP32_MUL_CHECK_ZERO_INFINITY(X,Y) CAT(_FP32_MUL_CHECK_, FP32_CMP_SIGN(X,Y))(FP32_INF)

#define _FP32_MUL_CHECK_OTHER_OTHER(X,Y) FP32_MUL_UNCHECKED(X,Y)
#define _FP32_MUL_CHECK_OTHER_ZERO(X,Y) CAT(_FP32_MUL_CHECK_, FP32_CMP_SIGN(X,Y))(FP32_0)
#define _FP32_MUL_CHECK_ZERO_OTHER(X,Y) CAT(_FP32_MUL_CHECK_, FP32_CMP_SIGN(X,Y))(FP32_0)

#define _FP32_MUL_CHECK_ZERO_ZERO(X,Y) CAT(_FP32_MUL_CHECK_, FP32_CMP_SIGN(X,Y))(FP32_0)

#define _FP32_MUL_CHECK_POS_POS(X) X
#define _FP32_MUL_CHECK_POS_NEG(X) FP32_NEG(X)
#define _FP32_MUL_CHECK_NEG_POS(X) FP32_NEG(X)
#define _FP32_MUL_CHECK_NEG_NEG(X) X

#define FP32_MUL_UNCHECKED(X,Y) FP32_MUL_EVAL(_FP32_MUL(FP32_EXPONENT(X),FP32_EXPONENT(Y),FP32_MANTISSA(X),FP32_MANTISSA(Y), FP32_CMP_SIGN(X,Y)))
#define FP32_MUL_EVAL(X) FP32_MUL_EVAL1(FP32_MUL_EVAL1(FP32_MUL_EVAL1(FP32_MUL_EVAL1(X))))
#define FP32_MUL_EVAL1(X) FP32_MUL_EVAL2(FP32_MUL_EVAL2(FP32_MUL_EVAL2(FP32_MUL_EVAL2(X))))
#define FP32_MUL_EVAL2(X) X

#define _FP32_MUL(EX,EY,MX,MY,S) _FP32_MUL_X(I32_ADD(EX,EY),U64_MULSHIFT32(MX,MY),S)
#define _FP32_MUL_X(E,M,S) CAT(_FP32_MUL_Y_,S)(E,M)
#define _FP32_MUL_Y_POS_POS(E,M) FP32_NORMALIZE(E,M)
#define _FP32_MUL_Y_POS_NEG(E,M) FP32_NEG(FP32_NORMALIZE(E,M))
#define _FP32_MUL_Y_NEG_POS(E,M) FP32_NEG(FP32_NORMALIZE(E,M))
#define _FP32_MUL_Y_NEG_NEG(E,M) FP32_NORMALIZE(E,M)

#endif